### ISSUE TITLE
Should the mapping output include the Schema?

### ISSUE THREAD

**Issue by 6a6d74** [w3c/csvw#100]
Neither JSON nor RDF mappings currently include details of the schema in the output graph - because we're interested in _data_ not _metadata_ ... and, in the case of the RDF mapping, all the metadata needed to interpret the data values is included in the RDF output anyway.

However, some may want to include a schema in the output. Should implementations offer an option to include the schema description in the output graph? This would add the following properties to the output graph:
- All direct annotations (including Common Properties) on the schema description object
- The aggregate set of Inherited Properties from the schema description, the parent table description and, if available, the parent table group description
- An array of column description objects, each including all direct annotations (including Common Properties) and Inherited Properties on the specified column description

**Comment by iherman** [comment]
I would rather opt for a reference from the generated data to the metadata. I realize this is not perfect because (a) the metadata may be provided by the user and (b) the full metadata is a merge of various files. Nevertheless, adding additional terms/triples to the output seems to be a bit of an overkill to me...

So something like

"csvw:metadata : [ "uri1", "uri2",... ]

and

<> csvw:metadata (<uri1> <uri2>) .

in JSON and Turtle, respectively

Ivan

> On 11 Dec 2014, at 12:42 , Jeremy Tandy notifications@github.com wrote:
> 
> Neither JSON nor RDF mappings currently include details of the schema in the output graph - because we're interested in data not metadata ... and, in the case of the RDF mapping, all the metadata needed to interpret the data values is included in the RDF output anyway.
> 
> However, some may want to include a schema in the output. Should implementations offer an option to include the schema description in the output graph? This would add the following properties to the output graph:
> 
>   • All direct annotations (including Common Properties) on the schema description object *The aggregate set of Inherited Properties from the schema description, the parent table description and, if available, the parent table group description
>   • An array of column description objects, each including all direct annotations (including Common Properties) and Inherited Properties on the specified column description
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by JeniT** [comment]
Agreed: a pointer back to the original CSV table and possibly the metadata should be sufficient.

**Comment by 6a6d74** [comment]
Agreed. Propose to use property http://www.iana.org/assignments/relation/describedBy to relate the CSV to the Metadata.

**Comment by 6a6d74** [comment]
References to this issue removed from the mapping documents. See pull request #111.
