### ISSUE TITLE
Merge (import) definition and common dc properties...

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#150]
I am not sure we should go down that route, but I though I would flag this so that at least we know about this...

The `title` property is defined as a natural language property. The merge of two tables handles these separately. So if metadata `A` has 

`
"title" : "Tree operations`
``

and metadata `B` has

`
"title" : { "fr" : "Operation sur des arbres" }
`

then the merge (provided `en` is set as a default language) results in:

`
"title" : { "en" : "Tree operations", "fr" : "Operation sur des arbres" {
`

However: the current document defines `title` for a column only. Ie, on a table level (as in all the examples, b.t.w.) the property to be used is `dc:title`. However, if in the examples `dc:title` is used, the merge algorithm seems to lead to `"dc:title":"Tree operations"` (and, actually, I am not even sure the algorithm is properly defined, because one of the values is an Atomic value, the other is an object, and this pair is not listed at the end of the algorithm.)

For this very case we can simply allow the `title` to be used on the table level. But the general issue of handling, say, `dc` properties still stands...

**Comment by gkellogg** [comment]
There are more problems with the merge algorithm and the title property. The current merge step is defined as follows:

> - If the property is a natural language property, the result is an object whose properties are language codes and where the values of those properties are arrays. **The suitable language code for the values is either explicit within the existing value or determined through the default language in the metadata document**; if it can't be determined the language code und should be used. The arrays should provide the values from A followed by those from B that were not already a value in A.

The problem here is that the `column language` and not the `default language` from the context is used to retrieve the appropriate title. By merging two documents together, this step does not take into consideration the `column language`.

We could change this rule, but it is probably done differently for `title` in a Column and `title` within a Template (another reason to re-name these).

I think the reason for different language semantics stems from the difference in describing metadata values and interpreting an annotated table, and `title` can come from the annotated table, so `title` is described to use the column language instead of the default language. It might be better if `title` simply uses the default language, and that is also used when creating embedded metadata. Basically, before extracting embedded metadata, merge user-defined and found metadata to extract embedded metadata, using the `@base` and `@language` from the merged metadata when creating the embedded metadata. Then, the column titles from the CSV will be interpreted the same as the metadata files, and merge will match.

Later, of course, you need to re-merge user-specified with embedded metadata, and then merge in found metadata. This all is rather cumbersome, but it's a consequence of the prioritization we give in the syntax document, and the need to establish dialect for processing the CSV from the metadata files.

**Comment by iherman** [comment]
I guess this is an issue for natural language properties at large.

AFAIK, we agreed that the `@language` term is for the text in the metadata (as opposed to the CSV file content). But isn't it then the easiest thing to say that when the embedded metadata is turned into a bona fide metadata, it should be used into a language text using the formalism that we already have, ie

`
{ "en" : "Title in English" }
`

using the language in... oops. Not clear where. If it is the dialect: we get back to the issue on what the dialect is really used for (we have discussed that elsewhere, do not remember where). That is not good. Maybe the cleanest thing is to rely on the Content-Language response header and/or an implementation dependent setting (and default to "en").

Ivan

> On 12 Jan 2015, at 22:47 , Gregg Kellogg notifications@github.com wrote:
> 
> There are more problems with the merge algorithm and the title property. The current merge step is defined as follows:
> 
>   • If the property is a natural language property, the result is an object whose properties are language codes and where the values of those properties are arrays. The suitable language code for the values is either explicit within the existing value or determined through the default language in the metadata document; if it can't be determined the language code und should be used. The arrays should provide the values from A followed by those from B that were not already a value in A.
> The problem here is that the column language and not the default language from the context is used to retrieve the appropriate title. By merging two documents together, this step does not take into consideration the column language.
> 
> We could change this rule, but it is probably done differently for title in a Column and title within a Template (another reason to re-name these).
> 
> I think the reason for different language semantics stems from the difference in describing metadata values and interpreting an annotated table, and title can come from the annotated table, so title is described to use the column language instead of the default language. It might be better if title simply uses the default language, and that is also used when creating embedded metadata. Basically, before extracting embedded metadata, merge user-defined and found metadata to extract embedded metadata, using the @base and @language from the merged metadata when creating the embedded metadata. Then, the column titles from the CSV will be interpreted the same as the metadata files, and merge will match.
> 
> Later, of course, you need to re-merge user-specified with embedded metadata, and then merge in found metadata. This all is rather cumbersome, but it's a consequence of the prioritization we give in the syntax document, and the need to establish dialect for processing the CSV from the metadata files.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
`dc:` properties, or any other common properties would be handled as suggested in #142. `title` is different, as there is a specific term definition: `{"title": {"@id": "csvw:title", "@container": "@language"}`, which is how the language variations are handled (with the small exception for `und`).

The merge section defines handling of common properties, such as `dc:title`:

> • If the property is a common property, the result is an array containing values from A followed by values from B not already in A. An array result having a single value uses that value as it's result.

But, there is a corner case: if `@language` is defined differently in different merged metadata documents, this could result in a string value of `dc:title`, for example, being interpreted differently; **this is actually true for all string properties, not just common properties**. I would say that Merge should be updated to say that common property values which include strings are expanded to the explicit version. For example, `"dc:title": "Tree operations"` in a metadata document with `@language: en`, would be changed to `"dc:title": {"@value": "Tree operations", "@language": "en"}` before merging. This could potentially be undone in the final step, but it's probably simplest to leave it in merged form, and deal with the JSON representation in that document. (IMO, this should be consistent with how JSON-LD Compact would deal with it).

An alternative would be to say that it's invalid to merge together metadata documents that don't have the same `@language` definition, which would keep the representation of all properties in merged metadata simple strings, rather than expanded JSON-LD type literals.

**Comment by iherman** [comment]
> On 22 Jan 2015, at 21:42 , Gregg Kellogg notifications@github.com wrote:
> 
> dc: properties, or any other common properties would be handled as suggested in #142. title is different, as there is a specific term definition: {"title": {"@id": "csvw:title", "@container": "@language"}, which is how the language variations are handled (with the small exception for und).

I am confused.

Am I allowed to use "title" as a table level property? If I read the document then the answer is no. I can only use "dc:title". Put it another way, "title" is not a common property. That is my issue.

> The merge section defines handling of common properties, such as dc:title:
> 
> • If the property is a common property, the result is an array containing values from A followed by values from B not already in A. An array result having a single value uses that value as it's result.
> 
> But, there is a corner case: if @language is defined differently in different merged metadata documents, this could result in a string value of dc:title, for example, being interpreted differently; this is actually true for all string properties, not just common properties. I would say that Merge should be updated to say that common property values which include strings are expanded to the explicit version. For example, "dc:title": "Tree operations" in a metadata document with @language: en, would be changed to "dc:title": {"@value": "Tree operations", "@language": "en"} before merging. This could potentially be undone in the final step, but it's probably simplest to leave it in merged form, and deal with the JSON representation in that document. (IMO, this should be consistent with how JSON-LD Compact would deal with it).

... and I would end up with a complex syntax no matter what if I merge metadata. I would hate that...

Ivan

> An alternative would be to say that it's invalid to merge together metadata documents that don't have the same @language definition, which would keep the representation of all properties in merged metadata simple strings, rather than expanded JSON-LD type literals.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
I don't think we can make `title` an inherited property, but I can add it as an optional property for `Table`.

Note that `table` is the only property which is interpreted relative to `@language`, and uses the _language map_ form, so other than for common properties, we don't have over complex processing in the face of different `@language` definitions for merged metadata.

**Comment by gkellogg** [comment]
Resolved in PR #169 and on http://www.w3.org/2015/01/28-csvw-minutes.html.
