### ISSUE TITLE
Reconsider Need for Core Tabular Data Model

### ISSUE THREAD

**Issue by gkellogg** [w3c/csvw#170]
As discussed in #145, Core Tabular Data can be derived from trivial _Annotated Tabular Data_ by setting `headerColumnCount` to 0 and allowing the default for the Column `name` to be `_col=N`. In general, `name` can be considered to be derived from `title`, if it exists, or set to `_col=N` otherwise. In such a way, the separate steps needed to transform a CSV to _Core Tabular Data_ can be removed in favor of a single _Annotated Tabular Data_ transformation, which takes advantage of metadata defaults in the absence of `title` or `name`.

Describing Core Tabular Data in the Syntax/Model could then be updated to describe such defaults, by effectively setting `headerRowCount=0` in user-supplied metadata.

The update to `name` can clarify this:

> `name` is an _optional_ atomic property, ... When retrieving the `name` of a column, the value is that set explicitly as a metadata property value, or the first value from `title`, considering the default language. If no such value exists, the value of `name` is `_col=N`, where `N` is the 1-based column number.

**Comment by JeniT** [comment]
I _think_ that this is a suggestion to merge the discussion of the Core Tabular Data Model and the Annotated Tabular Data Model in the model document, which I'm happy with.

I suggest we don't have a default column name like `_col=N` because that isn't consistent with the constraints on `varname` in the [URI Template spec](https://tools.ietf.org/html/rfc6570#section-2.3), so will cause headaches for people trying to create URL templates in metadata for such CSV files. Something like `_col.N` would work from that perspective.

**Comment by JeniT** [comment]
Editor action: Remove reference to Core Tabular Data Model; merge its content into Annotated Tabular Data Model
