### ISSUE TITLE
Appendix on JSON-LD restrictions

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#203]
The metadata document should include a (probably non-normative) appendix listing the restrictions v.a.v. JSON-LD

**Comment by gkellogg** [comment]
This appendix is in 4f626196cb19c8b1225d2ac52fc3b16ae692daaf and part of PR #281.

**Comment by JeniT** [comment]
I think this needs to be normative as implementations need to generate warnings/errors if the syntax doesn't follow those restrictions.

**Comment by JeniT** [comment]
Reading again, I think there are three things here:
1. What does an implementation that parses the metadata need to give errors/warnings about (to ensure that JSON-LD-aware processors will give the same results as non-JSON-LD-aware processors)?
2. How does an implementation need to normalise the values of common properties during the merge process (to provide a consistent basis for mapping into RDF & JSON)?
3. What are the restrictions in JSON-LD terms for general JSON-LD tool chains?

Of these, the last needs to go into the appendix but the first two are normative I think.

**Comment by gkellogg** [comment]
> I think this needs to be normative as implementations need to generate warnings/errors if the syntax doesn't follow those restrictions.

This should be taken care of when normalizing.

> 1. What does an implementation that parses the metadata need to give errors/warnings about (to ensure that JSON-LD-aware processors will give the same results as non-JSON-LD-aware processors)?

I think this is handled in normalization.

> 1. How does an implementation need to normalise the values of common properties during the merge process (to provide a consistent basis for mapping into RDF & JSON)?

This is described during merge normalization.

> 1. What are the restrictions in JSON-LD terms for general JSON-LD tool chains?

The main implication is that a normal JSON-LD processor might handle somethings that are outside of our dialect. It would seem to impose a burden on such implementations to check for these things, but I'll think about it some more.

**Comment by gkellogg** [comment]
My understanding is that an Appendix is normative unless it is marked as informative. This wouldn't be the first spec to have a normative appendix, and given that the JSON-LD are secondary to the thrust of the spec, an appendix seems appropriate to me.

**Comment by gkellogg** [comment]
So, thinking about this further, I think the JSON-LD Normalization can be moved into the Merge section, as it is specific to CSVW.

> 1. What does an implementation that parses the metadata need to give errors/warnings about (to ensure that JSON-LD-aware processors will give the same results as non-JSON-LD-aware processors)?

To ensure interoperability, problems found with common properties and notes should probably be errors, not warnings. This will ensure that if a regular JSON-LD processor is used, it will only process our dialect and there won't be any unexpected results. The downside is that we fail earlier.

As the Normalization section is written now, replacing "issue warning" with "raise error" will ensure than anything outside of our dialect will cause execution to abort so that only our dialect of JSON-LD will be issued.

Given this, an implementation could either use our abbreviated mechanism for generating RDF (to be written), or the JSON-LD toRdf algorithm and get the same results.

> 1. How does an implementation need to normalise the values of common properties during the merge process (to provide a consistent basis for mapping into RDF & JSON)?

The pre-merge steps include the following:

> If the property is a common property or notes the values must be normalized as described in section A.1 JSON-LD Normalization.

This will also ensure that any problems cause an error to be raised.

> 1. What are the restrictions in JSON-LD terms for general JSON-LD tool chains?

Given the above, I don't think there are any restrictions, as we will have detected anything which is out of spec.
