### ISSUE TITLE
type vs datatype in column metadata

### ISSUE THREAD

**Issue by rufuspollock** [w3c/csvw#22]
### Issue 1
- type vs datatype in fields/columns schema
  - type is used in Tabular Data Format but conflicts with dublin core type

```
columns: [
  {
    "name": "A",
    "type": "string"
  } 
  ...

vs

columns: [
  {
    "name": "A",
    "datatype": "string"
  }
```
### Issue 2
- datatype vs dataType
  - Camel-case is standard for json
  - But could be confusing and maybe datatype is one word

**Comment by JeniT** [comment]
Note that now we've reduced the scope of inclusion of Dublin Core vocabulary, so `type` could be used now (though there's still the potential of confusion with `@type`).

**Comment by JeniT** [comment]
Proposed resolution: We settle on `datatype` to indicate the datatype of the values in a column.

**Comment by rufuspollock** [comment]
@JeniT not sure I understand there - we can't expand datatype to be arbitrary types - it should be restricted. I understand from @iherman now that @ is being reserved so maybe we want something like your proposal or just rdfDataType or something.

**Comment by JeniT** [comment]
@rgrp I don't understand what you're saying either :) As I understood this issue, it's just about what to call the property that indicates the type of the values in a column (eg strings or number or dates). We've been using `datatype` in the spec for a while now so my proposed resolution is to close this issue saying that's the name that we'll use for this property (rather than `type` or `dataType`).

The list of the datatypes that are supported is at http://w3c.github.io/csvw/metadata/#datatypes - it is a list of fixed length (not arbitrary).

**Comment by rufuspollock** [comment]
I'm confusing this with the @datatype issue - sorry! On this one we are agreed on datatype and can close i think - apologies for confusion!

CLOSED. datatype is attribute name.
