### ISSUE TITLE
Which order to boolean conversions and default value placement occur in?

### ISSUE THREAD

**Issue by 6a6d74** [w3c/csvw#263]
Say that I have CSV data as shown below:

```
GID,On Street,Species,Trim Cycle,Diameter at Breast Ht,Inventory Date,Comments,Protected,KML
1,ADDISON AV,Celtis australis,Large Tree Routine Prune,11,10/18/2010,,,"<Point><coordinates>-122.156485,37.440963</coordinates></Point>"
2,EMERSON ST,Liquidambar styraciflua,Large Tree Routine Prune,11,6/2/2010,,YES,"<Point><coordinates>-122.156749,37.440958</coordinates></Point>"
```

and the _column description_ of the `Protected` column is:

```
    {
      "name": "protected",
      "title": "Protected",
      "dc:description": "Indication (YES / NO) whether the tree is subject to a protection order.",
      "datatype": {"base": "boolean", "format": "YES|NO"},
      "default": "NO"
    }
```

The first row of data has an empty value for the `Protected` column, clearly I want this to default to a `false` value.

Question is: does the placement of the `default` value happen before or after the `YES` or `NO` of the boolean has been converted to `true` or `false`?

If before, then `default` should be `NO` as shown above; if after, then the `default` value should be `false`.

The documentation does not provide sufficient information to determine this at present.

**Comment by iherman** [comment]
It strikes me that this is not specific to booleans. Eg, if the datatype is a date, the same question occurs: in what format would I put a default date in: is it the, say, M/D/YYYY format, or the ISO format?

If I try to put myself into the place of the author, I believe he/she would probably prefer to adapt to whatever the data contains, the ISO format is, for many, a kind of an administrative version that few people use in practice. Hence he/she would prefer to use the M/D/YYYY format. What this amounts to is that the default value should be used _before_ the the datatype conversion.

My 2 cents...

Ivan

> On 26 Feb 2015, at 04:17 , Jeremy Tandy notifications@github.com wrote:
> 
> Say that I have CSV data as shown below:
> 
> GID,On Street,Species,Trim Cycle,Diameter at Breast Ht,Inventory Date,Comments,Protected,KML
> 1,ADDISON AV,Celtis australis,Large Tree Routine Prune,11,10/18/2010,,,"<Point><coordinates>-122.156485,37.440963</coordinates></Point>"
> 2,EMERSON ST,Liquidambar styraciflua,Large Tree Routine Prune,11,6/2/2010,,YES,"<Point><coordinates>-122.156749,37.440958</coordinates></Point>"
> 
> and the column description of the Protected column is:
> 
> ```
> {
>   "name": "protected",
>   "title": "Protected",
>   "dc:description": "Indication (YES / NO) whether the tree is subject to a protection order.",
>   "datatype": {"base": "boolean", "format": "YES|NO"},
>   "default": "NO"
> }
> ```
> 
> The first row of data has an empty value for the Protected column, clearly I want this to default to a false value.
> 
> Question is: does the placement of the default value happen before or after the YES or NO of the boolean has been converted to true or false?
> 
> If before, then default should be NO as shown above; if after, then the default value should be false.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
From the steps in [Parsing Cells](http://w3c.github.io/csvw/metadata/#parsing-cells), I think that the behavior without a separator is clear:
1. unless the datatype is string or anyAtomicType or any, strip leading and trailing whitespace from the string value
2. if the resulting string is an empty string, apply the remaining steps to the string given by the default property
3. if the separator property is not null and the resulting string is an empty string, the cell value is an empty list
4. ...

So, an empty cell would take on the value of default ("NO" in @6a6d74's case), which would then fall on to datatype mapping, so would result in `false`.

However, if there was a separator, and the values were "Y,N,,Y", it would result in [true, false, "", true], as the empty string is not mapped using the current language.

A possible resolution to this would be to simply to re-work the steps so that dividing on separator is done first, and then trimming spaces. The net result is the same and reconciles this issue.

I'll do a PR for this.

**Comment by 6a6d74** [comment]
All good. Thanks for the clarification.
