### ISSUE TITLE
How should common properties be expanded based on @context

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#269]
In the [metadata merge](http://w3c.github.io/csvw/metadata/#merging-metadata) it currently says that "If the property is a common property the values are expended using using `@context`." (and in the changes @gkellogg has made in #258 this also applies to the `notes` property).

I don't think that there is any normalisation that can take place here, because processors don't know anything about common properties or the types of values that they might take (ie whether they are natural language properties to be assigned a language from the `@context` or link properties to be resolved against the base URL). As discussed in #142, processors should recognise and interpret certain structures in values (eg objects with `@language` or `@datatype` on them), but other than that I don't think that they should make any assumptions about the values of these properties.

For example, when faced with a `dc:title` property, I don't think processors should automatically assign the `@language` from the `@context` to that value.

If we want to make processors have built-in recognition for the types of common properties, then we have to define them somewhere in the specification, in a big list, for all the namespaces for all the prefixes that we recognise. I propose we do not do that.

**Comment by gkellogg** [comment]
Common properties are just JSON-LD, and they cannot also be natural-language properties. The properties have the interpretation given them by their `@context`. The reason for normalizing them is principally because `@language` (and to a lesser-degree `@base`) might be different in the metadata it comes from vs what would exist after the merge.

> For example, when faced with a dc:title property, I don't think processors should automatically assign the @language from the @context to that value.

In this case, you can't really say that the value of a common property is not JSON-LD. As, a string value of `dc:title`, to a JSON-LD processor, will have `@language` applied.

Processors do not need any understanding of the types of common properties, as this comes from the one-and-only `@context` we provide (other than local-variations using `@language` and `@base`). This, the string value of `dc:title`, or any other common property, or sub-value of a common property, should be interpreted as would a JSON-LD processor.

In practice, this is important (theoretically) only for RDF transformations. Not sure how to resolve this, we could consider changing `@language` to something else, so we don't conflate our rules with JSON-LD's; it's only used for `title`, so perhaps being explicit is the best rule.

There is also a theoretical issue with `@base` localization: if a common property were something like the following:

```
{ "@context": ["http://www.w3.org/ns/csvw", {"@base": "http://example.com/base/"}],
  "dc:source": {"@id": "rel"}
}
```

and this were merged into metadata with some other base, the URL value of `dc:source` would be interpreted relative to that location, not http://example.com/base/. This would be an issue even without an explicit `@base`, if for some reason the metadata files came from two different paths.

**Comment by JeniT** [comment]
@gkellogg I think we need to write out what normalisation based on the `@context` means for different kinds of values of common properties. I guess this needs to await the changes arising from #142 to see what it looks like.

**Comment by iherman** [comment]
> On 28 Feb 2015, at 15:40 , Gregg Kellogg notifications@github.com wrote:
> 
> Common properties are just JSON-LD, and they cannot also be natural-language properties. The properties have the interpretation given them by their @context. The reason for normalizing them is principally because @language (and to a lesser-degree @base) might be different in the metadata it comes from vs what would exist after the merge.
> 
> For example, when faced with a dc:title property, I don't think processors should automatically assign the @language from the @context to that value.
> 
> In this case, you can't really say that the value of a common property is not JSON-LD. As, a string value of dc:title, to a JSON-LD processor, will have @language applied.
> 
> Processors do not need any understanding of the types of common properties, as this comes from the one-and-only @context we provide (other than local-variations using @language and @base). This, the string value of dc:title, or any other common property, or sub-value of a common property, should be interpreted as would a JSON-LD processor.
> 
> In practice, this is important (theoretically) only for RDF transformations. Not sure how to resolve this, we could consider changing @language to something else, so we don't conflate our rules with JSON-LD's; it's only used for title, so perhaps being explicit is the best rule.

I think that would be wrong. I agree with @gellogg that the normalization step is a direct consequence of the F2F decisions. The @context applies, in terms of JSON-LD, to the graph that is the metadata description but which is, also, the same graph as what will be generated after the csv2rdf conversion; introducing a different term for language seems to be very misleading, nay, conceptually wrong. Because we define a JSON-LD Lite for the purpose of CSV, #142 means that the values should be normalized factoring in the @context local to that specific metadata file so that the right values are used after merge. The same is true for @base, ie, URI-s should be absolutize at that point. Sigh, I must say:-)

> There is also a theoretical issue with @base localization: if a common property were something like the following:
> 
> { "@context": ["http://www.w3.org/ns/csvw", {"@base": "http://example.com/base/"}],
>   "dc:source": {"@id": "rel"}
> }
> 
> and this were merged into metadata with some other base, the URL value of dc:source would be interpreted relative to that location, not http://example.com/base/.

What do the JSON-LD rules say for relative URI-s in this case? Because, again, we are operating in JSON-LD Lite, so we have to follow those rules...

Ivan

> This would be an issue even without an explicit @base, if for some reason the metadata files came from two different paths.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
> What do the JSON-LD rules say for relative URI-s in this case? Because, again, we are operating in JSON-LD Lite, so we have to follow those rules...

Relative URLs are handled differently depending on the property. `@type` is evaluated relative to `@vocab`, if it exists, or using a term definition. Properties with `@type: @vocab` are also evaluated the same way. Everything else is evaluated relative to the document base, or `@base` in the context; which is equivalent to our `base URL`.

The processing consequence is that values of common properties or notes should be evaluated recursively:
- If the property is `@id`, the value is a URL which should be made absolute using `base URL`
- If the property is `@type`, the value is a URL, which may be defined as a term in the context.
- If the value of a property is a string, it is a literal which may take it's language from `@language`.
- If it is an array, then each value is processed using this algorithm.
- If it is an object, then it is normalized recursively using this algorithm.

Note that this is not expansion, as we're not expanding the property keys themselves, nor are we forcing all values to be arrays. This essentially keeps the same shape of the common properties/notes, while reconciling `@language` and `base URL` from the metadata in which it is defined.

**Comment by iherman** [comment]
> On 01 Mar 2015, at 11:09 , Gregg Kellogg notifications@github.com wrote:
> 
> What do the JSON-LD rules say for relative URI-s in this case? Because, again, we are operating in JSON-LD Lite, so we have to follow those rules...
> 
> Relative URLs are handled differently depending on the property. @type is evaluated relative to @vocab, if it exists, or using a term definition. Properties with @type: @vocab are also evaluated the same way. Everything else is evaluated relative to the document base, or @base in the context; which is equivalent to our base URL.
> 
> The processing consequence is that values of common properties or notes should be evaluated recursively:
> 
>   • If the property is @id, the value is a URL which should be made absolute using base URL
>   • If the property is @type, the value is a URL, which may be defined as a term in the context.
>   • If the value of a property is a string, it is a literal which may take it's language from @language.
>   • If it is an array, then each value is processed using this algorithm.
>   • If it is an object, then it is normalized recursively using this algorithm.
> Note that this is not expansion, as we're not expanding the property keys themselves, nor are we forcing all values to be arrays. This essentially keeps the same shape of the common properties/notes, while reconciling @language and base URL from the metadata in which it is defined.

Right. But, JSON-LD, the "value is a URL which should be made absolute using base URL", both for @id or @type, would use the @base or the URL of the file itself, right? If so, we have no choice than using @base from @context as a part of a normalization step prior to merge.

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
> Right. But, JSON-LD, the "value is a URL which should be made absolute using base URL", both for @id or @type, would use the @base or the URL of the file itself, right? If so, we have no choice than using @base from @context as a part of a normalization step prior to merge.

The `base URL` is defined as either the location of the metadata file, or `@base` in the context. If we use that for `@type` we would be diverging from JSON-LD. By saying that we make file-relative URLs absolute using `base URL` we cover all the bases. We may want to restrict `@type` to being one of an Absolute URL, a prefixed name using one of the term definitions form our context, or a term from the context and say that anything else is either an error. The JSON-LD expansion algorithm would just return it as a relative URL, which could be an issue when turned into RDF, but does not explicitly handle this otherwise.

I don't see a way around doing this, but on the bright-side, by first normalizing the content, converting to JSON-LD becomes simpler.

I'll add some text for this, #142,  and #203.
