### ISSUE TITLE
Default attributes - schema.org vs dc terms vs ...

### ISSUE THREAD

**Issue by rufuspollock** [w3c/csvw#29]
The current spec offers a set of standard terms people could use as attributes on resources (whilst allowing more). What should these default terms be ...

**Comment by iherman** [comment]
Reproducing a [mail sent to the mailing list](http://lists.w3.org/Archives/Public/public-csv-wg/2014Oct/0006.html):

I was wondering how to move ahead with the schema.org/dcmi question, their normativeness, etc; we seem to be in an impasse at this moment. Here is a strategy that may help us moving forward. (Some of the issues below were also motivated by giving some more thoughts to the RDF/JSON conversion document and its possible implementation.)
1. We define a small set of core properties that we consider to be essential in the metadata. "We define" means that we specify the terms to be used in the metadata specification as well as their data types and intended meaning. There is already a set of such terms defined at the end of 3.4.2:
   - created
   - creator
   - description
   - language
   - license
   - modified
   - provenance
   - publisher
   - rights
   - rightsHolder
   - source
   - spatial
   - subject
   - temporal
   - title
   
   we may start there (although I am not sure 'spatial' and 'temporal' should be part of such core set of terms). (I actually believe that these terms should be used only as top level terms, at least in some cases; I am not sure it makes sense to add, say, a license to a specific cell in the table.)
2. The metadata already refers to @context. We would then say that (JSON-LD compatible) context entries MAY be added by the author to assign these terms to explicit URI-s in the vocabulary of their choice. The metadata document would also include an informative appendix with @context examples for a mapping on DCT or to schema.org. That being said, I foresee that many authors would not really bother, in fact, and just use the terms in JSON.
3. The current 3.3.1 section in the metadata document (listing the Dublin Core terms) should be removed altogether.
4. The metadata document should also make it possible to use any set of properties anywhere in the metadata _in qualified form. We should also refer to a number of predefined prefixes; the best approach is, probably, to refer to the RDFa predefined prefix set. Ie, people may add properties of the form "dc:spatial" or "schema:author". However, authors may also add prefixes they want, besides those that are predefined. For many users, that is where it stops; others, who care about a proper RDF-ization of the metadata, may want to add the proper mapping of the prefixes to URI-s; we should provide a @context for the predefined prefixes as well.

I believe this approach could work, and covers our issues:
- users (authors, clients) who do not really care about URI-s, linkage, RDF formats, or indeed vocabularies, could simply rely on the terms that are defined as standard terms in the metadata document. (I believe this is what Jeni proposed on our meeting 10 days ago.)
- users who care about binding the terms to outside vocabularies can choose to add a set of URI mappings through a context; whether they choose DC, schema.org, or some application area specific vocabulary is not for the standard to define, although we make it easy to use the well known vocabularies. That also means that neither the DC reference nor the schema.org reference is normative.
- with the appropriate contexts the metadata is proper JSON-LD, ie, can serve as a 'glue' between the core CSV data and the Linked Data Cloud. (It is important to note that, afaik, a context can be delivered to a client via HTTP links, ie, the publisher of the data may not even care about the @context but the data store may ensure the JSON-LD aspects nevertheless.)
- the RDF mapping of the CSV content would rely on context if present, otherwise these terms would be mapped against the `csv:` namespace. That means the mapping to RDF becomes clearly defined. (The current CSV->RDF document is hand-wawing around the top level terms right now, it is not really clean yet)
- users can use any other types of vocabularies at their heart's content, and the proper usage and mapping of these vocabularies can be ensured through the usage of qualified names to separate those from the terms that are defined by our standard.
  How does that sound?

Ivan

[1] http://www.w3.org/TR/vocab-dcat/
[2] http://www.w3.org/2011/rdfa-context/rdfa-1.1

**Comment by 6a6d74** [comment]
Ivan - this sounds like a reasonable approach ... I like the suggestion to remove the normative references to Dublin Core and Schema.org.

Essentially, you're saying that the _normative_ metadata for a CSV dataset would include, say, `license`. The semantics of `license` are clear - and should be defined in the CSV metadata TR.

A data publisher _may_ choose to use a JSON-LD @context to map `license` onto schema.org (`https://schema.org/license`), Dublin Core (`http://purl.org/dc/terms/license`) or any other target that they deem is appropriate.

The only caveat (problemette ... a small problem :-) ) with this is that the data publisher _must_ map the normative metadata term such as `license` onto an entity with equivalent semantics. There is nothing (except common sense) preventing a data publisher using @context to map `license` onto `http://example.org/def/somethingElseEntirely`.

**Comment by iherman** [comment]
On 06 Oct 2014, at 09:31 , Jeremy Tandy notifications@github.com wrote:

> Ivan - this sounds like a reasonable approach ... I like the suggestion to remove the normative references to Dublin Core and Schema.org.
> 
> Essentially, you're saying that the normative metadata for a CSV dataset would include, say, license. The semantics of license are clear - and should be defined in the CSV metadata TR.

Yes.

> A data publisher may choose to use a JSON-LD @context to map license onto schema.org (https://schema.org/license), Dublin Core (http://purl.org/dc/terms/license) or any other target that they deem is appropriate.

Yes. And the operative word is 'may':-)

> The only caveat (problemette ... a small problem :-) ) with this is that the data publisher must map the normative metadata term such as license onto an entity with equivalent semantics. There is nothing (except common sense) preventing a data publisher using @context to map license onto http://example.org/def/somethingElseEntirely.

Yes, that is indeed true. We cannot prevent people shooting in their own feet...

A slightly more sophisticated metadata validator (if that exists) may prevent this by knowing about some of the common vocabularies that people use for something like licence and may check against that. But that is clearly not water proof...

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C 
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
GPG: 0x343F1A3D
WebID: http://www.ivan-herman.net/foaf#me

**Comment by iherman** [comment]
Note: some additional discussions happened on the IG mailing list. To have a trace on github I have put a reference to all here:

http://lists.w3.org/Archives/Public/public-csv-wg/2014Oct/0008.html (DanBri)
http://lists.w3.org/Archives/Public/public-csv-wg/2014Oct/0010.html (Ivan's response)
http://lists.w3.org/Archives/Public/public-csv-wg/2014Oct/0011.html (Gregg's response on the previous)
http://lists.w3.org/Archives/Public/public-csv-wg/2014Oct/0012.html (Ivan's response)
http://lists.w3.org/Archives/Public/public-csv-wg/2014Oct/0007.html (Rufus' response to the original mail)
http://lists.w3.org/Archives/Public/public-csv-wg/2014Oct/0009.html (Ivan's response)

**Comment by rufuspollock** [comment]
On call today agreed, normative set are:
- created
- creator
- description
- language
- license
- modified
- [provenance](not sure vs source)
- publisher
- rights
- rightsHolder
- source
- subject
- title

Excluded: (people can add themselves)
- spatial
- temporal

**Comment by JeniT** [comment]
At the October 2014 F2F at TPAC, we resolved to cut down the number of unprefixed metadata terms to the bare minimum, namely `language` for tables and columns, and `title` for columns. All other metadata will need to have a prefix (ie `dc:description`). We're hoping that the [Data on the Web Best Practices](https://www.w3.org/2013/dwbp/wiki/Main_Page) group will recommend which metadata publishers should use.
