### ISSUE TITLE
CSV2RDF should defer cell processing as much as possible

### ISSUE THREAD

**Issue by gkellogg** [w3c/csvw#290]
Individual cell processing seems to duplicate much of what’s described in [Parsing Cells](http://w3c.github.io/csvw/metadata/#parsing-cells) in the metadata document. The main diversion is the use of the `ordered` annotation, have we agreed to that? In any case, this might be better described within Parsing Cells leave the result of this to the Tabular Data Model description of [cell value](http://w3c.github.io/csvw/syntax/#dfn-cell-value) and [cell value URL](http://w3c.github.io/csvw/syntax/#dfn-cell-value-url).

**Comment by 6a6d74** [comment]
@gkellogg, thanks for explaining this a little more on the call yesterday ... I think I see the section you are talking about.

Personally, I don' t think that the csv2rdf algorithm is talking about _parsing_ at all. In contrast, in order to figure out how to output the content, I need to:

1) determine if `valueUrl` has been set - in which case the node is an IRI
2) determine if the cell value contains a sequence of values (even an empty sequence) - which I do by checking if the `separator` property has been set (I don't actually care _WHAT_ the separator is - only that it has been set) ... if the sequence is ordered (if the `ordered` property has value `true`) then the node is an instance of `rdf:List` which contains literal nodes for the sequence values ... else it is an unordered sequence and literal nodes are created for each of the values in the sequence
3) (for the remaining single value case) determine if the cell value is not null - in which case the single node is a literal.

No parsing of the cell value - just trying to determine what to do with the pre-parsed value.

**Comment by iherman** [comment]
Having gone through the text yesterday, I think it is good as is in this respect...

Ivan

> On 05 Mar 2015, at 04:02 , Jeremy Tandy notifications@github.com wrote:
> 
> Thanks for explaining this a little more on the call yesterday ... I think I see the section you are talking about.
> 
> Personally, I don' t think that the csv2rdf algorithm is talking about parsing at all. In contrast, in order to figure out how to output the content, I need to:
> 
> 1) determine if valueUrl has been set - in which case the node is an IRI
> 1) determine if the cell value contains a sequence of values (even an empty sequence) - which I do by checking if the separator property has been set (I don't actually care WHAT the separator is - only that it has been set) ... if the sequence is ordered (if the ordered property has value true) then the node is an instance of rdf:List which contains literal nodes for the sequence values ... else it is an unordered sequence and literal nodes are created for each of the values in the sequence
> 1) (for the remaining single value case) determine if the cell value is not null - in which case the single node is a literal.
> 
> No parsing of the cell value - just trying to determine what to do with the pre-parsed value.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by iherman** [comment]
Can we close this issue? The CSV2\* documents seem to be fairly consistent here...

**Comment by gkellogg** [comment]
Yes, I'm satisfied
