### ISSUE TITLE
Where does row numbering begin?

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#32]
At the moment (e.g., in the RDF/JSON conversions) there is a notion of a row number. It is not clear whether the header row (if present) should count or not, or whether row numbers begins at the first data row (with number 1).

**Comment by JeniT** [comment]
The [tabular data model](http://w3c.github.io/csvw/syntax/#core-tabular-data-model) doesn't include a header row, only data rows, and the numbering of these start from 1. When a CSV file that includes a header row gets parsed into a tabular data model, the headers become annotations on the columns, not a separate row.

The bit that's then confusing is that [RFC7111](http://tools.ietf.org/html/rfc7111) for fragids on CSV files specifies that the header row _is_ counted, so if a given CSV file contains a header row then `#row=1` refers to that header row and `#row=2` to the first data row. So if a metadata file includes some notes then the references will all be out-by-one.

Note that there might be source CSV files that include multiple header lines, and skipped columns, and so on, so that we're already in the case where the fragid references that you'd want to use to reference into a CSV file might not match with the numbering of the rows/columns in the data model. See https://github.com/w3c/csvw/issues/50. Perhaps annotations should reference cells etc through something other than fragids?

**Comment by JeniT** [comment]
I chatted with the chairs of the Annotations WG. It would be possible for the target of an annotation to be referred to via a structured object rather than through a URL, so we could use that to make the numbering of the rows/columns match up.

**Comment by yakovsh** [comment]
RFC 4180 has a notion of a header which is optional

**Comment by JeniT** [comment]
Yes, CSV syntax has the notion of a header row but the [tabular data model](http://w3c.github.io/csvw/syntax/#model) doesn't.

**Comment by iherman** [comment]
I think the possible decision (and, in my understanding, was discussed on the corridors at TPAC) that both the RDF and the JSON mapping would include a reference to the original cells in terms of RFC7111. But then... does it mean that we have to store the information somewhere whether the original data had or did not have header row(s)?

**Comment by JeniT** [comment]
@iherman is there enough here to answer your question about where row numbering begins or is this still not clear in the specs? Can we mark it closed? Do we need to open a separate issue about annotations and about references to rows/columns/cells from within RDF & JSON?

**Comment by iherman** [comment]
Hm. I understand that the row numbering for the data should begin by 1. I think that is clear. But I am a bit bothered by the fact that we may not be able to use RFC7111, although it may really be useful and would simplify many things like the annotations.

However: now that we have the dialect description in the metadata, we may have enough information to do that. Isn't it correct that the first data row, at least as far as rfc7111 is concerned, starts at headerRowCount+skipRows? If so, we can combine these two: conceptually, the row numbering begins by 1, but, if rfc7111 is used, we use that value. Ain't pretty, but I am not sure we have a choice.

In any case, because these issues are around, I think adding an informal section in the metadata document that makes the relationship to rfc7111 clear and would make these things explicit would really be helpful.

**Comment by danbri** [comment]
See http://www.w3.org/2015/02/12-csvw-irc#T15-42-15

**Comment by JeniT** [comment]
Resolved at Feb F2F: in the annotated data model, rows have both a number (the number in the data model) and a source-number (the original line number from the source CSV file). These may be different.

`_row` in URI templates references the row number in the model, and we agree to introduce a `_sourcerow` (or something) to be used to reference the source number (line from the CSV file).

**Comment by 6a6d74** [comment]
Both csv2rdf and csv2json docs now refer to both (table) row number (integer value) and row source (RFC 7111 fragment id) in _standard_ mode output.
