### ISSUE TITLE
Minor CSV2RDF notes

### ISSUE THREAD

**Issue by gkellogg** [w3c/csvw#327]
- [x] Step 4 says "Each table is processed sequentially in the order they are referenced in the table group description." Order is not relevant in RDF output. It might be if there was an `ordered` flag for TableGroups, but I don't believe there is.
- [x] If in standard mode, should there be a statement linking G to T? I use `csvw:table`, but perhaps it should be `csvw:resources` as the TableGroup is the TableGroup, and not a description of it. (standard mode only, of course).
- [x] I find 4.5.5 very confusing. It seems to me that it could be simplified by using node `R` as the subject for each cell, unless it is determined by aboutUrl. Then, simply process each non-suppressed cell. In particular in 4.5.5.1, it's important that every cell not having an aboutUrl use the _same_ blank node. This does mean that a row may describe itself; if this is an issue, establish yet another row-level BNode to use as the default cell subject, but I don't see that as an problem.

**Comment by 6a6d74** [comment]
Responding in-line:

> Step 4 says "Each table is processed sequentially in the order they are referenced in the table group description." Order is not relevant in RDF output. It might be if there was an ordered flag for TableGroups, but I don't believe there is.

You're correct to point out that ordering doesn't matter in RDF; there's no need to assert in the algorithm that the rows must be processed in order! I propose to remove this line. Will also remove the line indicating sequential ordering of Rows (step 4.5) and cells (step 4.5.5.3). (PR coming!)

> If in standard mode, should there be a statement linking G to T? I use csvw:table, but perhaps it should be csvw:resources as the TableGroup is the TableGroup, and not a description of it. (standard mode only, of course).

Yes; you're right. Adding text in PR coming your way.

> I find 4.5.5 very confusing. It seems to me that it could be simplified by using node R as the subject for each cell, unless it is determined by aboutUrl. Then, simply process each non-suppressed cell. In particular in 4.5.5.1, it's important that every cell not having an aboutUrl use the same blank node. This does mean that a row may describe itself; if this is an issue, establish yet another row-level BNode to use as the default cell subject, but I don't see that as an problem.

Introduction of the subject node S is necessary because the row may describe several subjects - see the [music event listing example](http://w3c.github.io/csvw/csv2rdf/#example-events-listing). I also think that the _row_ is disjoint from the _subject resource_ that is described by the row ... even if there's only one (unidentified) subject.

**Comment by gkellogg** [comment]
See bcf65c72256d52e81e210ba4713ac2d5b61a6734. I think this really simplifies row processing and results in the same triples.
