### ISSUE TITLE
Marking tables as right-to-left in the media type

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#46]
An alternative approach is for the CSV to be parsed into a table model in which the columns are numbered in the reverse, for tables which are either marked as or detected to be right-to-left tables. For example, we could introduce a `bidi=rtl` or similar media type parameter, and use this to determine whether the first column in table generated from the CSV is the text before the first comma in each line or the text after the last comma in the line.

**Comment by yakovsh** [comment]
I am hesitant to put this in the mime type itself. If we are able to define a document which provides the syntax, then that would be a good place to indicate this.

Also, I am not aware of any other MIME type that indicates bi-directionality via the mime type itself

**Comment by JeniT** [comment]
+1 I'm not in favour of doing this via the media type either; I think the current design works. We should get it checked by the i18n WG to make sure.

**Comment by JeniT** [comment]
Suggested resolution: no action, except to ask for i18n WG to review. @iherman when/how should we do that?

**Comment by iherman** [comment]
For this, I think we can ask them at any time. I would suggest to do that after the F2F.

**Comment by JeniT** [comment]
Blocked pending publication of next WD.

**Comment by JeniT** [comment]
@JeniT to ask I18N WG explicitly about this issue.

**Comment by JeniT** [comment]
Done so at https://lists.w3.org/Archives/Public/public-csv-wg/2015Jun/0036.html

**Comment by r12a** [comment]
this is a personal view, yet to be discussed with others in the i18n WG.  These are ideas off the top of my head, and may need further discussion.

i don't know how common it is for people to create visually-ordered columns, but i would hope that it is not widespread. On that basis, i think we should be careful not to imply that using visually-ordered columns is an equally viable approach to that of logically-ordered columns.  I suspect that defining a media-type would lend undue credence to the visual approach, but also cause confusion as to the intended application.

i think that care needs to be taken to clarify that this only affects column direction.

my inclination would be to prefer some non-media-type metadata associated with the table that has the name column-direction and that only needs to be used if the column direction is different to the text direction of the table. Values could be visual-rlt and visual-ltr.

does that make sense?

**Comment by matial** [comment]
From my experience with bidi-enabled software dealing with tables (e.g. Microsoft Excel and Word), the direction of a table mainly determines whether the first logical column is on the left side (for LTR) or on the right side (for RTL). It may also set the default text direction for cell content, but this is secondary.
In a CSV file, the text before the leftmost comma in each line goes to the first column, etc...
This first column will be displayed on the left or the right side depending on the table direction, as explained above. The first column, whatever the side on which it is displayed, is always column A.
If the software allows dynamic setting of the table direction, then when the user changes it, all the columns are redisplayed so that A, B, C becomes C, B, A.

Note that the table direction should not determine text direction within cells too strictly. In a bidi environment, it is very common that there will be textual content (e.g. captions, names) which must have RTL direction, and numbers which should have LTR direction.
