### ISSUE TITLE
Add changes since last WD

### ISSUE THREAD

**Issue by gkellogg** [w3c/csvw#481]
- [x] Metadata
- [x] Syntax
- [x] CSV2RDF
- [x] CSV2JSON
- [x] Use Cases

**Comment by iherman** [comment]
Added the changes sections for csv2rdf and csv2json, see PR #484

**Comment by iherman** [comment]
Adding the LCCR label for the use case document, the other documents are done.

**Comment by 6a6d74** [comment]
@iherman - the only material additions to the UCR doc are:
1. a new use case to cover open validation modes - [Use Case #25 - Consistent publication of local authority data](http://w3c.github.io/csvw/use-cases-and-requirements/index.html#UC-ConsistentPublicationOfLocalAuthorityData)
2. addition of acknowledgements section by @gkellogg 

Note that ISSUE #205 (to rework the requirements) is still outstanding.

Would you be so kind as to create the "update since last release" section? Many thanks ...

**Comment by iherman** [comment]
Jeremy, did we plan to publish the UCR this week? I do not think so… So I would propose to do that in a few weeks when things have been settled otherwise…

Ivan

> On 13 Apr 2015, at 16:41 , Jeremy Tandy notifications@github.com wrote:
> 
> @iherman - the only material additions to the UCR doc are:
> 1. a new use case to cover open validation modes - Use Case #25 - Consistent publication of local authority data
> 2. addition of acknowledgements section by @gkellogg
> 
> Note that ISSUE #205 (to rework the requirements) is still outstanding.
> 
> Would you be so kind as to create the "update since last release" section? Many thanks ...
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by 6a6d74** [comment]
No - I don't think so ... But it was on the list :-) ... Just kidding

**Comment by 6a6d74** [comment]
Changes since last section now added in PR #808
