### ISSUE TITLE
Relationship to Data Cube

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#509]
(Copied from [mail of Benedikt Kaempgen](http://www.w3.org/mid/0D7BFFD7C415144DA75C3D49C46AC2153780461A@ex-ms-1a.fzi.de))

> Hello,
> 
> I am wondering about the relationship to the CSV on the Web efforts and the QB vocabulary [1].
> 
> Thanks for your efforts, I think, the use case to have CSV files on the web as a compact data representation and RDF for describing the meaning of the data is very interesting.
> 
> Best
> 
> Benedikt
> 
> [1] http://www.w3.org/TR/vocab-data-cube/

**Comment by 6a6d74** [comment]
Re-opening to enable us to capture dialogue with Benedikt Kaempgen

**Comment by 6a6d74** [comment]
Hi Benedikt - I always had an eye on using the [RDF Data Cube](http://www.w3.org/TR/vocab-data-cube/) as output from the CSV to RDF conversion. 

To illustrate use of the RDF Data Cube for converted CSV data I have created a real example - based on historical weather observations published by the [Met Office](http://www.metoffice.gov.uk). The example is described [here](https://github.com/w3c/csvw/blob/gh-pages/examples/rdf-data-cube-example.md).

Please let us know if this illustrates what you need to know.

**Comment by 6a6d74** [comment]
I have simplified the json-ld syntax in the metadata descriptions (and the `.md` file that provides the description) so that instances of datatype boolean, double and string use the simple form as discussed in yesterday's CSVW wg teleconf.

Note that I have also forced values of `dc:format` to _not_ refer to a language -
noting that language is specified by default in the context, therefore:

`dc:format": {"@value": "text/plain”}`

replaces

`"dc:format": "text/plain”`

(see merged PR #526)

**Comment by 6a6d74** [comment]
No response from originator received since [answer](https://lists.w3.org/Archives/Public/public-csv-wg-comments/2015Apr/0001.html) provided on 27-April-2015

https://lists.w3.org/Archives/Public/public-csv-wg-comments/2015Apr/0001.html

**Comment by 6a6d74** [comment]
_Response from originator (14-July-2015) cross posted:_

Thank you for your answer. Unfortunately, since I am not subscribed to public-csv-wg-comments, I only found it now.

[Your example](https://github.com/w3c/csvw/blob/gh-pages/examples/cambornedata-snippet-standard.ttl) is interesting.

I am wondering whether based on your work it would be possible to have a more compact representation of a qb:DataSet with:

1) A definition of a qb:DataSet with a link to the metadata of a CSV file and a link to the CSV file (or links to rows in a CSV file)
2) A definition of a qb:DataStructureDefinition with links to instances of qb:DimensionProperty, qb:MeasureProperty, and qb:AttributeProperty, each with links to columns in the CSV file.

Given the data and metadata one could have an algorithm similar to the [QB Normalization algorithm](http://www.w3.org/TR/vocab-data-cube/#normalize-algorithm) to translate this compact to a normalized qb:DataSet.

Best

Benedikt

**Comment by 6a6d74** [comment]
_Cross-posted [response (from public-comment mailing list)](https://lists.w3.org/Archives/Public/public-csv-wg-comments/2015Jul/0003.html):_

Hi- 

There are likely to be many improvements that can be made to the RDF Data Cube implementation that I used in my example :-)

From reading your response, I think you are suggesting that the `qb:DataStructureDefinition` could be coupled directly to the metadata description of the columns in the CSV file - effectively short-cutting the process of generating a compact RDF data cube?

I had not thought of this approach and it certainly may provide some optimisation. However, developing such a normalization algorithm is beyond the scope of the CSV on the web Working Group. 

I believe that there is a proposal to establish a community group related to working with tabular data on the web - primarily to look at developing richer, template-based transformation mechanisms. (at present, I am unsure of the status of this proposal- apologies)

If you are able to create a normalization algorithm such as you suggest above, it would be interesting to share your work in this community group.
