### ISSUE TITLE
Controlled vocabulary for table-direction

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#51]
The values of `table-direction` should be a defined controlled vocabulary in JSON-LD, so that the values map on to URIs in the RDF version rather than strings. We invite comment on how to configure the JSON-LD context to enable these values to be interpreted in this way.

**Comment by JeniT** [comment]
@gkellogg do you have any ideas about how to manage this?

**Comment by gkellogg** [comment]
Yes. `table-direction` needs to be defined using `"@type": "@vocab"`, and each of `rtl`, `ltr`, and `default` also need to be defined in the vocabulary, and can then be used as values of `table-direction`. For example:

```
{
  "@context": {
    "@vocab": "http://www.w3.org/ns/csvw/",
    ...
    "table-vocab": {"@type": "@vocab"},
  },
  "@id": "..",
  "table-vocab": "ltr"
}
```

In this case, because there's a default vocabulary, we don't actually need to define `ltr`, but it is treated as a vocabulary term. In RDFS it should be an instance of some appropriate class.

**Comment by JeniT** [comment]
@gkellogg assigning this to you to do, if you haven't already. (And if you have, please close.)

**Comment by gkellogg** [comment]
It's done in the namespace by creating a `csvw:Direction` class having `rtl`, `ltr`, and `default` as instances, and then using `csvw:Direction` as the range of `table-direction` and `text-direction`.

**Comment by gkellogg** [comment]
`owl:oneOf` might be more closed, which we could do if you think it's better.
