### ISSUE TITLE
Document the requirement for content negotiation to retrieve the JSON-LD context document

### ISSUE THREAD

**Issue by hubgit** [w3c/csvw#528]
For a while, I was puzzled by the use of `http://www.w3.org/ns/csvw` as the `@context` property in [the Metadata Vocabulary document](https://w3c.github.io/csvw/metadata/#json-ld-context), as normally this would be the URL of a JSON-LD context document. In this case, opening http://www.w3.org/ns/csvw in a web browser appears to load a HTML page.

Then I realised that fetching it with an appropriate Accept header would retrieve the JSON-LD version of the document: `curl -H 'Accept: application/ld+json' 'http://www.w3.org/ns/csvw'`.

Given that the JSON-LD context document is also available at http://www.w3.org/ns/csvw.jsonld would it make sense to use that as the `@context` URL instead, or to at least document the requirement for an appropriate Accept header?

**Comment by gkellogg** [comment]
Just to clarify, the metadata document has the form of JSON- LD, including a proscribed context, but the processing steps. (In general) do not process it as JSON-LD.

That said, it's intirely appropriated to use this URL to reference the context, since, if a JSON-LD processor does parse it, it will request the context using content negotiation on application/ld+json.

Also, note that all three files returned from www.w3.org/ns/csvw are also RDFS vocabularies, so it's also appropriated to use the same URI to allow a client to retrieve an appropriate version, and not bind any URL to a specific serialization format.

**Comment by iherman** [comment]
(Additionally to what @gkellogg said) The JSON-LD spec does say, I presume (have not checked) that the `@context` points at a JSON-LD file. Ie, a processor should ask for a json-ld file if and when dereferencing the file...

That being said, adding a half-sentence into http://w3c.github.io/csvw/metadata/index.html#h-json-ld-context may not harm.

**Comment by iherman** [comment]
@hubgit, in view of the additional note (and #541) can we close this issue, ie, does it answer to your original question?

**Comment by hubgit** [comment]
Yes, that's great, thanks @lherman and @gkellogg.
