### ISSUE TITLE
Should there be limitations on the syntax of column names?

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#53]
What syntactic limitations should there be on column names to make them most useful when used as the basis of conversion into other formats, bearing in mind that different target languages such as JSON, RDF and XML have different syntactic limitations and common naming conventions.

**Comment by JeniT** [comment]
Note constraints in [RFC 6570 (URI Templates)](https://tools.ietf.org/html/rfc6570)

**Comment by gkellogg** [comment]
Also, if the metadata indicates two or more header columns, how is this interpreted by a processor?

**Comment by JeniT** [comment]
@gkellogg I don't understand, can you give an example?

**Comment by gkellogg** [comment]
Yes, I realize now that the extracted header rows are different from the name of the column. I guess this is most closely related to the `title` rather than the `name` metadata. However, it does come into play for an uninformed-mapping, where there is no metadata, and presumably the column header is used to construct the default `name`.

If we have a CSV with two header rows, such as the [Use Case #12](http://www.w3.org/TR/2014/WD-csvw-ucr-20140327/#UC-ChemicalStructures):

```
5
methane molecule (in angstroms)
C        0.000000        0.000000        0.000000
H        0.000000        0.000000        1.089000
H        1.026719        0.000000       -0.363000
H       -0.513360       -0.889165       -0.363000
H       -0.513360        0.889165       -0.363000
```

I think that this shows four columns where the first column is the only one with a header cell, which is the two values ["5", "methane molecule (in angstroms)"].

The metadata document states the following:

> If the column already has a title annotation (because a header row has been included in the original CSV file) then a validator must issue a warning if the existing title annotation is not the same as any of the possible column titles.

Is this one title or two? How must this correspond to `title` information from the metadata?

(This seems to be off-topic for this issue, but may need to be tracked someplace, anyway).

**Comment by JeniT** [comment]
Currently the spec contains a SHOULD constraining the syntax for column names.

Proposed resolution:
- we change the SHOULD constraint to a MUST (better feedback for users)
- we ensure that when a `title` is used to generate a `name` that the result satisfies the syntactic constraints, by normalising the title (this will need to be pretty harsh!)
- we ensure that the default `name` that's used when there's no other information is consistent with the syntactic constraints; see #180

**Comment by iherman** [comment]
Due to the limitation of terms usable in templates, we do not really have a choice...

**Comment by danbri** [comment]
See http://www.w3.org/2015/02/12-csvw-irc#T11-20-33

**Comment by JeniT** [comment]
Resolved at Feb F2F to change 'SHOULD' to 'MUST' re column name syntax restrictions. See #197.

Other things are in progress.
