### ISSUE TITLE
CSVM @context clarification

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/csvw#634]
I didn't see any response to my 19-Jun-2015 message about this:
https://lists.w3.org/Archives/Public/public-csv-wg/2015Jun/0075.html

Regarding the @context requirement for a metadata document, the spec is 
not clear that if the value of @context is an array, then the string 
"http://www.w3.org/ns/csvw" must be the _first_ element of that array. 
I suggest changing the wording in section 5.2 
http://w3c.github.io/csvw/metadata/#h-top-level-properties
to something like:

"An array composed of a string (as the first element) and an object (as 
the second element), where the string is http://www.w3.org/ns/csvw"

**Comment by gkellogg** [comment]
I don't see why we can't make such a constraint, and it would simplify finding the particular metadata. However, I'm not sure we can require `@context` to be the first member of the object, as neither JSON nor JSON-LD make any requirements about ordering of object members. Indeed, some implementations may not be able to guarantee this. So, the value of ensuring that the namespace URI appears first may be diminished.

**Comment by akuckartz** [comment]
@gkellogg Perhaps I misunderstand something, but @dbooth-boston suggested to state a requirement for the first element of an _array_, not for the ordering of _object members_.

**Comment by gkellogg** [comment]
@akuckartz Yes, I understand, and I'm not against doing this. However, if the reason to do it is to make it simpler to detect a CSVW context, this may be mitigated by not being able to predict precisely where the `@context` will appear. It doesn't change processing otherwise, so it may be a requirement without a sufficient motivation. It's certainly open for discussion, and I wouldn't stand against adding such a requirement.

Presumably, the usefulness of this would be to use `@context: /http://www.w3.org/ns/csvw` in a regular expression to serve as a magic number for the MIME type (see #631). If we don't also mandate that `@context` appear as the first member, which we may not be able to, then we can't create a reasonable regular expression, and the motivation may be moot.

Up for discussion on the next telecon.

**Comment by dbooth-boston** [comment]
@gkellogg The reason is not for magic number detection.  It is just for clarity and simplicity.  I am not suggesting that the ordering of _object members_ be constrained.

**Comment by gkellogg** [comment]
I updated this in 0a9f35186d0504e08473c9f630ec9a373795424e (on a separate branch related to #631 for now), as I believe the order was intended.

**Comment by JeniT** [comment]
+1 for fixing this order

**Comment by danbri** [comment]
seems harmless enough, so +1
