### ISSUE TITLE
Register of recognised date-time picture string formats

### ISSUE THREAD

**Issue by 6a6d74** [w3c/csvw#65]
As discussed in #54 there needs to be a list of picture string formats for date-times that are recognised when validating / mapping CSV.

Should this list be enshrined within the REC (e.g. as a normative part of the metadata vocal)? ... 

Inevitably we will have missed someone's favourite; should we allow user-defined "experimental" terms to be used (like for mime-types; e.g. prefixed by `x-` such as `x-mypicturestringformat`? (obviously this breaks interoperability but provides some flexibility)

Should this list be maintained outside the REC (e.g. as a register to which other "blessed formats" can be added)?

Noting that this requires governance arrangements to be put in place for maintaining this list - either by updating the REC or managing some official list.

The list so far includes:
- unicode (from [TR35](http://www.unicode.org/reports/tr35/tr35-dates.html#Date_Format_Patterns)) 
- xpath3 (from [XPath and XQuery functions](http://www.w3.org/TR/xpath-functions-30/#formatting-dates-and-times))
- simpledateformat (from [Java](https://docs.oracle.com/javase/6/docs/api/java/text/SimpleDateFormat.html))
- python-datetime (from [Python](https://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior))
- ruby-datetime (from [Ruby](http://www.ruby-doc.org/stdlib-1.9.3/libdoc/date/rdoc/DateTime.html))
- [momentjs](http://momentjs.com/docs/#/displaying/)

For each of these, there needs to be a persistent reference to the documentation that describes the picture-string format plus, optionally, details of any implementations.

Note that for `simpledataformat` there are both Java and [JavaScript](https://code.google.com/p/jaxson/source/browse/trunk/jaxson/WebRoot/jsSrc/org/jaxson/util/SimpleDateFormat.js?r=41) implementations ... so I don't think it's appropriate to tie this specifically to Java.

For python and ruby's `datetime` they're almost the same but not quite :-(

Are there others? 

What is the URI for authoritative documentation for each of these?

What tokens should be used within the JSON metadata?

**Comment by 6a6d74** [comment]
This is a metadata vocab issue as we need to define _either_ the authoritative list _or_ where the list lives.

This is a mapping issue as we need to refer to the authoritative list (either in metadata vocab or externally). In either case, support for a given picture-string format is implementation dependent.

**Comment by iherman** [comment]
> On 27 Nov 2014, at 11:47 , Jeremy Tandy notifications@github.com wrote:
> 
> As discussed in #54 there needs to be a list of picture string formats for date-times that are recognised when validating / mapping CSV.
> 
> Should this list be enshrined within the REC (e.g. as a normative part of the metadata vocal)? ...
> 
> Inevitably we will have missed someone's favourite; should we allow user-defined "experimental" terms to be used (like for mime-types; e.g. prefixed by x- such as x-mypicturestringformat? (obviously this breaks interoperability but provides some flexibility)
> 
> Should this list be maintained outside the REC (e.g. as a register to which other "blessed formats" can be added)?
> 
> Noting that this requires governance arrangements to be put in place for maintaining this list - either by updating the REC or managing some official list.
> 
> The list so far includes:
> 
>   • unicode (from TR35)
>   • xpath3 (from XPath and XQuery functions)
>   • simpledateformat (from Java)
>   • python-datetime (from Python)
>   • ruby-datetime and Ruby)
>   • momentjs
> For each of these, there needs to be a persistent reference to the documentation that describes the picture-string format plus, optionally, details of any implementations.
> 
> Note that for simpledataformat there are both Java and JavaScript implementations ... so I don't think it's appropriate to tie this specifically to Java.
> 
> For python and ruby's datetime they're almost the same but not quite :-(
> 
> Are there others?
> 
> What is the URI for authoritative documentation for each of these?

The reason we'd define these as URI-s is because if the metadata is seen as a JSON-LD, then these become predicates, ie, we need to have that as URI-s. There is no other reason, is there? If so: the same question arise for all the properties we use: the WG defines these terms with a clear specification on what they mean, and we probably map all the terms, in a @context, to the same namespace that we will define.

I think the real issue is how the conformance clause refers to these. Ie, is an implementation required to implement/recognize any of those. My take is: no. In which case we define the list but they are not really normative.

If we want to say 'yes', then we are bound to use terms that refer to stable standards. That means unicode and xpath3, I do not see anything else.

xpath3 is actually, as far as I can see, not a picture string, just defines the default literal format, right? In which case we can also say that this is what a conformant processor must recognize (ie, no conversion).

Ivan

> What tokens should be used within the JSON metadata?
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by JeniT** [comment]
we decided 14/1/2015 we didn't need this
