### ISSUE TITLE
At Risk feature during CR: usage or not .well-known

### ISSUE THREAD

**Issue by iherman** [w3c/csvw#691]
Just opening a separate issue related to the "At Risk" feature in current CR. It used to be issue #555 leading to the official CR draft, taking it a separate issue now on whether the feature is to be kept or not.

**Comment by iherman** [comment]
Copying [Melvin Carvalho's](http://www.w3.org/mid/CAKaEYhKebjOscrNgyQyfasMgXCK_m8dGapvnOW7=_Rn1jny+Vw@mail.gmail.com) comment from the mailing list to the issue because some remarks are also relevant.

> Just following on from the discussion on the TAG mailing list.  In the SoLiD specification [1] we are currently using meta data to associate more data with resources on the Linked Data Platform.
> 
> Having gone through rel="meta" we have now decided to align with this groups work and use rel="describedBy" for general meta data associated with files.
> 
> We also use rel="acl" for access control lists, but that's not (yet) registered with IANA, perhaps we will use a full URI.
> 
> In general, we will always try and supply the correct header to point clients to the meta data.  Typically it is of the form .meta or .acl (though previously we had been using ,meta)
> 
> I personally support the points made by David Booth which suggest that using the .well-known pattern is more appropriate for _per site_ wide configurations, rather than, for _per directory_ or _per resource_ type data.
> 
> My own interest in tabular data is limited, however one use case I have looked at in the past is for payments where systems such as paypal would use a csv for bulk upload of payments.  
> 
> In our work we are seeing more and more the use of the web, not only as a cross origin data space, but also as a cross directory, data space.  In systems where you dont have access to .well-known or are limited to a directory (dropbox / gdrive / sky drive / box.net perhaps?) I can see in general a probe sequence starting close to the file's directory making sense.
> 
> Hope that helps!
> 
> [1] https://linkeddata.github.io/SoLiD/

**Comment by dbooth-boston** [comment]
I believe the .well-known feature should be dropped from the
CSVW specification -- or in the very least, users should be
_discouraged_ from using it -- for at least the following
reasons:
1. The RFC 5785 .well-known mechanism is inappropriate for
   this use.  It is intended for **site-wide** policy data,
   and that is _not_ the granularity of control that is needed
   or desired for file- or directory-specific CSV metadata.
2. The .well-known feature is dangerous because a CSV author
   may publish a CSV file on a large site that specifies
   one metadata file pattern in its .well-known file (or
   has no .well-known file), and later that .well-known
   file may be changed by the site administrator, without
   the CSV file owner's knowledge, to specify a different
   pattern, thus causing CSVW processors to either not find
   the metadata file or find a different metadata file than
   the CSV author intended.  This scenario is described here:
   https://lists.w3.org/Archives/Public/www-tag/2015Jul/0007.html
3. This use of .well-known violates the intent of RFC5785.
   Section 1.1 (Appropriate Use of Well-Known URIs) explicitly
   states:
   
   "well-known URIs are not intended
   for general information retrieval or establishment of large
   URI namespaces on the Web.  Rather, they are designed to
   facilitate discovery of information on a site **when it
   isn't practical to use other mechanisms**"   [my emphasis]

But in this case, it clearly _is_ practical to use other
mechanisms.  The CSVW spec already provides at least three
alternate mechanisms for associating CSV metadata with CSV data:
(a) a Link header, which can point from a CSV data URI to its
corresponding CSV metadata URI; (b) standard CSV metadata URI
patterns; and (c) the ability to publicize non-standard URIs
of CSV metadata documents that link to their corresponding CSV
data files.  (To clarify that last mechanism, one mode of use
is for a user to start with a CSV data URI, and from that seek
the corresponding CSV metadata.  But another mode of use is
for a user to start with the CSV metadata URI, and from that
locate the corresponding CSV data.  To facilitate that mode
of use, data publishers have the option of publicizing their
CSV metadata URIs along with their CSV data, so that users
can easily find the CSV metadata.  Given the CSV metadata,
CSVW processor can then automatically locate the corresponding
CSV data, because the CSV metadata file explicitly links to
its corresponding data file.)
1. The CSVW working group's decision to include this feature
   was based on deference to the TAG's advice, which which
   was flawed based on incorrect assumptions.  As explained in
   some detail in the threads below, the use of .well-known is
   NOT needed to avoid harmful URI squatting as the TAG had
   assumed when it considered this issue.  The fact that the
   TAG has not taken the time to correct that mistake is NOT
   a good reason for the CSVW working group to perpetuate it.
   https://lists.w3.org/Archives/Public/www-tag/2015Jun/0011.html
   https://www.w3.org/Search/Mail/Public/search?keywords=booth&hdr-1-name=subject&hdr-1-query=.well-known&index-grp=Public_FULL&index-type=t&type-index=www-tag
   https://www.w3.org/Search/Mail/Public/search?keywords=booth&hdr-1-name=subject&hdr-1-query=.well-known&index-grp=Public_FULL&index-type=t&type-index=public-csv-wg
2. When a poll was sent to public-csv-wg@w3.org asking about
   potential use of the .well-known feature, NOBODY indicated
   that they needed and intended to use that feature.  We should
   not include a feature with so little demonstrated need.
   https://lists.w3.org/Archives/Public/public-csv-wg/2015Jun/0085.html

**Comment by iherman** [comment]
Discussed on [telco](http://www.w3.org/2015/10/07-csvw-minutes.html): planning decision in a week, 14th; until then, reaching out to the data publishers in the group to see if the `.well-known` mechanism is of importance/interest. If yes, the mechanism stays as is, if not, we will consider removing it.

**Comment by iherman** [comment]
For the records: I will not be on the call on the 14th; as I do not have any strong feeling either way, I am o.k. with any decision the group will make.

**Comment by JeniT** [comment]
As of 14th October, we’ve had two comments indicating that we should remove the `.well-known` behaviour for CSV metadata. Currently our intention is therefore to remove it. We’re looking for comments in the next week to counteract these. /cc @mnot

**Comment by gkellogg** [comment]
I'll create a provisional PR to remove .well-known from the documents and test suite.

**Comment by mnot** [comment]
David commented:

> The RFC 5785 .well-known mechanism is inappropriate for this use. It is intended for site-wide policy data, and that is not the granularity of control that is needed or desired for file- or directory-specific CSV metadata.

... and later ...

> This use of .well-known violates the intent of RFC5785. Section 1.1 (Appropriate Use of Well-Known URIs) explicitly states: "well-known URIs are not intended for general information retrieval or establishment of large URI namespaces on the Web. Rather, they are designed to facilitate discovery of information on a site when it isn't practical to use other mechanisms" [my emphasis]

These are essentially the same points, and also that which Melvin makes.

As an author of RFC5785, I can assure you that the intent of the specification was not to rule out use cases such as this; indeed, one of its first uses was WebFinger, which did something very much along these lines; see [RFC7033](http://tools.ietf.org/html/rfc7033).

That dispensed with, David later comments:

> The .well-known feature is dangerous because a CSV author may publish a CSV file on a large site that specifies one metadata file pattern in its .well-known file (or has no .well-known file), and later that .well-known file may be changed by the site administrator, without the CSV file owner's knowledge, to specify a different pattern, thus causing CSVW processors to either not find the metadata file or find a different metadata file than the CSV author intended. This scenario is described here: https://lists.w3.org/Archives/Public/www-tag/2015Jul/0007.html

There are myriad ways an administrator can screw their users, from MIME type extension mappings to CSP configuration to .htaccess processing conventions; the list goes on. The answer for all of these pitfalls is the same; administrators of shared resources need to be careful about changing configuration without proper notification and testing. 

Moving on, David says:

> But in this case, it clearly is practical to use other mechanisms. The CSVW spec already provides at least three alternate mechanisms for associating CSV metadata with CSV data: (a) a Link header, which can point from a CSV data URI to its corresponding CSV metadata URI; 

Great. 

> (b) standard CSV metadata URI patterns; and 

This is, I think, the heart of the issue. I don't mind if you don't decide to use .well-known; what I mind is "standard URI patterns" for all of the reasons discussed with the TAG.

> (c) the ability to publicize non-standard URIs of CSV metadata documents that link to their corresponding CSV data files. (To clarify that last mechanism, one mode of use
> is for a user to start with a CSV data URI, and from that seek the corresponding CSV metadata. But another mode of use is for a user to start with the CSV metadata URI, and from that locate the corresponding CSV data. To facilitate that mode of use, data publishers have the option of publicizing their CSV metadata URIs along with their CSV data, so that users can easily find the CSV metadata. Given the CSV metadata, CSVW processor can then automatically locate the corresponding CSV data, because the CSV metadata file explicitly links to its corresponding data file.)

Great.

I think the real question is -- given that you have (a) and (c), do you really need (b)?

David continues:

> The CSVW working group's decision to include this feature was based on deference to the TAG's advice, which which was flawed based on incorrect assumptions. As explained in some detail in the threads below, the use of .well-known is NOT needed to avoid harmful URI squatting as the TAG had
> assumed when it considered this issue. The fact that the TAG has not taken the time to correct that mistake is NOT a good reason for the CSVW working group to perpetuate it.

The TAG read and discussed your feedback (see [meeting minutes](https://github.com/w3ctag/meetings/blob/gh-pages/2015/07-ber/07-16-minutes.md) and [issue](https://github.com/w3ctag/spec-reviews/issues/55)). 

Our advice stands, even if you disagree with it. Also, we took a considerable amount of time on calls with @JeniT, as well as F2F time discussing this; please don't mischaracterise our effort just because you don't agree with the outcome.

Again, you're correct that we don't need .well-known, provided that (b) is removed.

**Comment by dbooth-boston** [comment]
On 10/16/2015 03:29 AM, Mark Nottingham wrote:

> David commented:
> 
> ```
> The RFC 5785 .well-known mechanism is inappropriate for this use. It
> is intended for site-wide policy data, and that is not the
> granularity of control that is needed or desired for file- or
> directory-specific CSV metadata.
> ```
> 
> ... and later ...
> 
> ```
> This use of .well-known violates the intent of RFC5785. Section 1.1
> (Appropriate Use of Well-Known URIs) explicitly states: "well-known
> URIs are not intended for general information retrieval or
> establishment of large URI namespaces on the Web. Rather, they are
> designed to facilitate discovery of information on a site when it
> isn't practical to use other mechanisms" [my emphasis]
> ```
> 
> These are essentially the same points, and also that which Melvin makes.

Yes, pretty much.

> As an author of RFC5785, I can assure you that the intent of the
> specification was not to rule out use cases such as this;

Sure, it should not be ruled out, because there may not be any better 
alternative in some cases.  But it should be _discouraged_.

> indeed, one of
> its first uses was WebFinger, which did something very much along these
> lines; see RFC7033 http://tools.ietf.org/html/rfc7033.
> 
> That dispensed with, David later comments:
> 
> ```
> The .well-known feature is dangerous because a CSV author may
> publish a CSV file on a large site that specifies one metadata file
> pattern in its .well-known file (or has no .well-known file), and
> later that .well-known file may be changed by the site
> administrator, without the CSV file owner's knowledge, to specify a
> different pattern, thus causing CSVW processors to either not find
> the metadata file or find a different metadata file than the CSV
> author intended. This scenario is described here:
> https://lists.w3.org/Archives/Public/www-tag/2015Jul/0007.html
> ```
> 
> There are myriad ways an administrator can screw their users, from MIME
> type extension mappings to CSP configuration to .htaccess processing
> conventions; the list goes on.

Right, but the fact that other risks already exist does not justify 
adding a new risk to the list.

> The answer for all of these pitfalls is
> the same; administrators of shared resources need to be careful about
> changing configuration without proper notification and testing.
> 
> Moving on, David says:
> 
> ```
> But in this case, it clearly is practical to use other mechanisms.
> The CSVW spec already provides at least three alternate mechanisms
> for associating CSV metadata with CSV data: (a) a Link header, which
> can point from a CSV data URI to its corresponding CSV metadata URI;
> ```
> 
> Great.
> 
> ```
> (b) standard CSV metadata URI patterns; and
> ```
> 
> This is, I think, the heart of the issue.I don't mind if you don't
> decide to use .well-known; what I mind is "standard URI patterns" for
> all of the reasons discussed with the TAG.

Please provide pointers to the exact reasons.  Making vague claims of 
"all of the reasons discussed with the TAG" gets is nowhere.  I have 
carefully analyzed and responded to all of the concerns that I was able 
to find.  As far as I can determine, the TAG concern about "standard URI 
patterns" boils down to a concern that it causes harmful URI squatting. 
  I have already dispensed with that concern by explaining in detail why 
this particular use of "standard URI patterns" does _not_ cause URI 
squatting.  I have been unable to find any other concern.  If there are 
other concerns, please say what the are or point me to them.

> ```
> (c) the ability to publicize non-standard URIs of CSV metadata
> documents that link to their corresponding CSV data files. (To
> clarify that last mechanism, one mode of use
> is for a user to start with a CSV data URI, and from that seek the
> corresponding CSV metadata. But another mode of use is for a user to
> start with the CSV metadata URI, and from that locate the
> corresponding CSV data. To facilitate that mode of use, data
> publishers have the option of publicizing their CSV metadata URIs
> along with their CSV data, so that users can easily find the CSV
> metadata. Given the CSV metadata, CSVW processor can then
> automatically locate the corresponding CSV data, because the CSV
> metadata file explicitly links to its corresponding data file.)
> ```
> 
> Great.
> 
> I think the real question is -- given that you have (a) and (c), do you
> really need (b)?

The answer to that is simple: It is not absolutely needed, but it is 
likely to be helpful to the user community by allowing people to _first_ 
search for .csv files, and _then_ automatically find the corresponding 
metadata file.  That workflow is assumed to be more intuitive to many 
users than first searching for CSV metadata files (and then 
automatically finding their corresponding CSV files).

> David continues:
> 
> ```
> The CSVW working group's decision to include this feature was based
> on deference to the TAG's advice, which which was flawed based on
> incorrect assumptions. As explained in some detail in the threads
> below, the use of .well-known is NOT needed to avoid harmful URI
> squatting as the TAG had
> assumed when it considered this issue. The fact that the TAG has not
> taken the time to correct that mistake is NOT a good reason for the
> CSVW working group to perpetuate it.
> ```
> 
> The TAG read and discussed your feedback (see meeting minutes
> https://github.com/w3ctag/meetings/blob/gh-pages/2015/07-ber/07-16-minutes.md

I see this perfunctory mention of my comments:
[[
Subtopic: CSV on the Web issue. 
https://github.com/w3ctag/spec-reviews/issues/55

hadley: I think this is out of our hands.

Hadley: looking at David Booth's concerns on .well-known

mnot: we have a fundamental disagreement on whether or not this is an 
ongoing issue. We went through a process to look at it, discuss it with 
him and the editors, and we all seem satisfied with it. He may be less 
pleased, but I'm not sure it can be helped.

dka: Closing then, especially since JeniT said her issues brought to the 
TAG were resolved on the telecons.
]]

AFAICT from those minutes, that looks to me like mnot _asserting_ to 
others in the TAG that the TAG should not bother to look at the issue 
further: "We went through a process to look at it, . . . and we all seem 
satisfied with it".  I see no evidence whatsoever that my point that 
this use of standard URI naming does _not_ cause URI squatting[1] was 
actually considered or discussed by anyone in the TAG.  The evidence 
above suggests the opposite: that my point was completely ignored by the 
TAG.

> and issue https://github.com/w3ctag/spec-reviews/issues/55).

That thread also does not in any way address my point that this use of 
standard URI patterns does _not_ cause URI squatting.

> Our advice stands, even if you disagree with it. Also, we took a
> considerable amount of time on calls with @JeniT
> https://github.com/JeniT, as well as F2F time discussing this; please
> don't mischaracterise our effort just because you don't agree with the
> outcome.

Sorry, but I can only go by the evidence that is recorded.  I cannot 
guess what is in anyone's mind.  And I see no evidence whatsoever that 
the TAG actually considered and understood the fact that this particular 
use of standard URI patterns does _not_ cause harmful URI squatting.[1] 
  All recorded evidence that I have seen suggests that the TAG _does_ 
believe that this use of standard URI patterns would cause  URI 
squatting.  And that is the only concern that I have seen the TAG express.

> Again, you're correct that we don't need .well-known, provided that (b)
> is removed.

But you have not shown that .well-known is needed, _given_ that this 
particular use of standard URI patterns does _not_ cause URI squatting.

A simple test of whether a standard URI pattern causes URI squatting is 
to ask: Does this mechanism _prevent_ URI owners from using those URI 
patterns for unrelated purposes?   If the answer is yes, then it causes 
URI squatting and should not be adopted.  If the answer is no, then it 
does not cause URI squatting.  In the case of standard patterns for CSV 
metadata, the answer is no, as explained in detail in [1].

> —
> Reply to this email directly or view it on GitHub
> https://github.com/w3c/csvw/issues/691#issuecomment-148637068.
1. https://lists.w3.org/Archives/Public/www-tag/2015Jun/0026.html

**Comment by iherman** [comment]
A semi-procedural fact that we should take into account in this discussion. 

_If_ the `.well-known` mechanism is dropped from the specification, we cannot replace with anything at this juncture. The specifications are in CR, and any new mechanism, URI pattern or otherwise, would require a new CR round because it is adding new functionalities. Due to the charter timing (the group's charter runs out in February), upcoming Xmas period, the time it takes to get a full voting round before a document becomes a Recommendation, etc, makes a second CR undoable. As a consequence, the only choice we have is to either drop `.well-known`, and not having anything replacing option (b) in @mnot's comment, or incorporate `.well-known` as it is today in the document. Discussing the pros and cons of URI patterns will not change that…

**Comment by dbooth-boston** [comment]
On 10/16/2015 11:53 AM, Ivan Herman wrote:

> A semi-procedural fact that we should take into account in this discussion.
> 
> /If/ the |.well-known| mechanism is dropped from the specification, we
> cannot replace with anything at this juncture. The specifications are in
> CR, and any new mechanism, URI pattern or otherwise, would require a new
> CR round because it is adding new functionalities. Due to the charter
> timing (the group's charter runs out in February), upcoming Xmas period,
> the time it takes to get a full voting round before a document becomes a
> Recommendation, etc, makes a second CR undoable. As a consequence, the
> only choice we have is to either drop |.well-known|, and not having
> anything replacing option (b) in @mnot https://github.com/mnot's
> comment, or incorporate |.well-known| as it is today in the document.
> Discussing the pros and cons of URI patterns will not change that…

I think you need to be a little clearer.  There are at least three 
choices available that would not add new functionalities:
1. keep |.well-known| in the spec as is;
2. drop |.well-known| but keep the standard URI pattern; or
3. drop the standard URI pattern (and |.well-known|).

If |.well-known| is kept I think there should at least be a warning in 
the spec stating that the feature is controversial, that very few people 
(nobody?)[2] indicated an actual need and intent to use the feature, and 
the working group did not have time to completely consider its merits 
before the end of its charter.

> —
> Reply to this email directly or view it on GitHub
> https://github.com/w3c/csvw/issues/691#issuecomment-148752937.

References
2. https://lists.w3.org/Archives/Public/public-csv-wg/2015Jun/0085.html

**Comment by iherman** [comment]
> On 16 Oct 2015, at 19:24, David Booth notifications@github.com wrote:
> 
> On 10/16/2015 11:53 AM, Ivan Herman wrote:
> 
> > A semi-procedural fact that we should take into account in this discussion.
> > 
> > /If/ the |.well-known| mechanism is dropped from the specification, we
> > cannot replace with anything at this juncture. The specifications are in
> > CR, and any new mechanism, URI pattern or otherwise, would require a new
> > CR round because it is adding new functionalities. Due to the charter
> > timing (the group's charter runs out in February), upcoming Xmas period,
> > the time it takes to get a full voting round before a document becomes a
> > Recommendation, etc, makes a second CR undoable. As a consequence, the
> > only choice we have is to either drop |.well-known|, and not having
> > anything replacing option (b) in @mnot https://github.com/mnot's
> > comment, or incorporate |.well-known| as it is today in the document.
> > Discussing the pros and cons of URI patterns will not change that…
> 
> I think you need to be a little clearer. There are at least three
> choices available that would not add new functionalities:
> 1. keep |.well-known| in the spec as is;
> 2. drop |.well-known| but keep the standard URI pattern; or

That is not an option. This alternative is not in the current CR; adding that would mean a new feature added to the spec. The options are:
- metadata supplied by the user of the implementation that is processing the tabular data
- metadata in a document linked to using a Link header associated with the tabular data file
- metadata located through a site-wide location configuration [this is the .well-known]
- metadata embedded within the tabular data file itself

http://www.w3.org/TR/2015/CR-tabular-data-model-20150716/#locating-metadata

> 1. drop the standard URI pattern (and |.well-known|).
> 
> If |.well-known| is kept I think there should at least be a warning in
> the spec stating that the feature is controversial, that very few people
> (nobody?)[2] indicated an actual need and intent to use the feature, and
> the working group did not have time to completely consider its merits
> before the end of its charter.

I do not agree adding such a note with this wording; it would be inappropriate for a W3C Recommendation.

Ivan

> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/w3c/csvw/issues/691#issuecomment-148752937.
> 
> References
> 2. https://lists.w3.org/Archives/Public/public-csv-wg/2015Jun/0085.html
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by dbooth-boston** [comment]
I think the bottom line is:
1. mnot has asserted a theoretical harm (URI squatting) -- which I have shown in detail to be unfounded -- if |.well-known| is _not_ kept. 
2. _Nobody_ has expressed both an actual need for |.well-known| and an intent to use it.  (I.e., a _real_ need as opposed to an imagined theoretical need.)
3. A feature without _actual_ need does not belong in the spec.

**Comment by dbooth-boston** [comment]
On 10/16/2015 01:34 PM, Ivan Herman wrote:

> > On 16 Oct 2015, at 19:24, David Booth notifications@github.com wrote:
> > . . .
> > If |.well-known| is kept I think there should at least be a warning in
> > the spec stating that the feature is controversial, that very few people
> > (nobody?)[2] indicated an actual need and intent to use the feature, and
> > the working group did not have time to completely consider its merits
> > before the end of its charter.
> 
> I do not agree adding such a note with this wording; it would be
> inappropriate for a W3C Recommendation.

It would not look pretty, but it would reflect reality.

**Comment by dbooth-boston** [comment]
On 10/16/2015 01:34 PM, Ivan Herman wrote:

> > On 16 Oct 2015, at 19:24, David Booth notifications@github.com wrote:
> > . . .
> > 2. drop |.well-known| but keep the standard URI pattern; or
> 
> That is not an option. This alternative is not in the current CR;
> . . .
> http://www.w3.org/TR/2015/CR-tabular-data-model-20150716/#locating-metadata

Huh???   Wow, my apologies.  I did not realize that the standard URI 
pattern had been dropped.  But now I see that it has.

In that case |.well-known| is attempting to prevent a "harm" that does 
not even exist, because there is no "standard URI pattern" for CSVW!

**Comment by iherman** [comment]
Well... Having looked at the situation again, if we drop the current .well-known option, the only real way of getting to the metadata of a csv file is the http header option. Both other options are implementation specific. My personal opinion is that this is very poor because most authors have no way of specifying a return header. All in all, my choice is to keep the current spec as is.

Ivan

---

Ivan Herman
Tel:+31 641044153
http://www.ivan-herman.net

(Written on mobile, sorry for brevity and misspellings...)

**Comment by dbooth-boston** [comment]
On 10/16/2015 02:38 PM, Ivan Herman wrote:

> Well... Having looked at the situation again, if we drop the current
> .well-known option, the only real way of getting to the metadata of a
> csv file is the http header option.

No, the author can also _publicize_ the metadata URIs, along with the 
CSV URIs, instead of expecting users to _only_ look for CSV URIs. 
Search engines will be able to find the metadata files automatically 
(from their MIME types), and from them, their associated CSV files.

**Comment by iherman** [comment]
Yes, that is also a possibility. But to me it falls under the "why make it simple if you can do it complicated" for the user. Sorry to be sarcastic, but an average data publisher would not simply trust the search engines to do the work, and may not know the tricks to manipulate the search engines to do so instantaneously. (Actually, I would not know what to do either)

Ivan

---

Ivan Herman
Tel:+31 641044153
http://www.ivan-herman.net

(Written on mobile, sorry for brevity and misspellings...)

**Comment by dbooth-boston** [comment]
On 10/16/2015 03:09 PM, Ivan Herman wrote:

> Yes, that is also a possibility. But to me it falls under the "why make
> it simple if you can do it complicated" for the user. Sorry to be
> sarcastic, but an average data publisher would not simply trust the
> search engines to do the work, and may not know the tricks to manipulate
> the search engines to do so instantaneously. (Actually, I would not know
> what to do either)

Well, to make it really simple for users a standard URI pattern is 
needed.  Even if that is not in the spec, I hope that implementations 
will at least automatically look (as a heuristic guess) for metadata 
using standard URI patterns, even if the spec does not _require_ them to 
do so.  It would always be safe for implementations to do so, because 
they could ignore any file they found that did not turn out to be the 
desired CSV metadata.

It is a shame that the fear of URI squatting prevented this heuristic 
from being mandated in the spec, since URI squatting turned out to be a 
red herring in the end.  But implementations could still help their 
users with this heuristic in spite of its absence in the spec.

**Comment by iherman** [comment]
> On 16 Oct 2015, at 20:33, David Booth notifications@github.com wrote:
> 
> On 10/16/2015 01:34 PM, Ivan Herman wrote:
> 
> > > On 16 Oct 2015, at 19:24, David Booth notifications@github.com wrote:
> > > . . .
> > > 2. drop |.well-known| but keep the standard URI pattern; or
> > 
> > That is not an option. This alternative is not in the current CR;
> > . . .
> > http://www.w3.org/TR/2015/CR-tabular-data-model-20150716/#locating-metadata
> 
> Huh??? Wow, my apologies. I did not realize that the standard URI
> pattern had been dropped. But now I see that it has.
> 
> In that case |.well-known| is attempting to prevent a "harm" that does
> not even exist, because there is no "standard URI pattern" for CSVW!

David, the standard URI option has been dropped _in favour_ of the `.well-known`, because the latter supersedes the former (see the example in the document). Ie, your characterization is not entirely fair.

**Comment by iherman** [comment]
> On 16 Oct 2015, at 21:59, David Booth notifications@github.com wrote:
> 
> On 10/16/2015 03:09 PM, Ivan Herman wrote:
> 
> > Yes, that is also a possibility. But to me it falls under the "why make
> > it simple if you can do it complicated" for the user. Sorry to be
> > sarcastic, but an average data publisher would not simply trust the
> > search engines to do the work, and may not know the tricks to manipulate
> > the search engines to do so instantaneously. (Actually, I would not know
> > what to do either)
> 
> Well, to make it really simple for users a standard URI pattern is
> needed.

I am happy we agree on this.

> Even if that is not in the spec, I hope that implementations
> will at least automatically look (as a heuristic guess) for metadata
> using standard URI patterns, even if the spec does not _require_ them to
> do so. It would always be safe for implementations to do so, because
> they could ignore any file they found that did not turn out to be the
> desired CSV metadata.
> 
> It is a shame that the fear of URI squatting prevented this heuristic
> from being mandated in the spec, since URI squatting turned out to be a
> red herring in the end. But implementations could still help their
> users with this heuristic in spite of its absence in the spec.

And I do not think we would do due diligence if we did not provide a standard way of providing a general mechanism. Just relying on various implementation options is not satisfactory.

I maintain my opinion that, at this point, the only reasonable option is to publish the document as is.

**Comment by dbooth-boston** [comment]
On 10/17/2015 03:39 AM, Ivan Herman wrote:

> David, the standard URI option has been dropped _in favour_ of the
> `.well-known`, because the latter supersedes the former (see the
> example in the document). Ie, your characterization is not entirely fair.

Oh, I see: you are viewing this as an exclusive either-or choice between 
providing a standard URI pattern and |.well-known|.  That is not what I 
had understood when |.well-known| was added to the spec -- and 
apparently I did not adequately check.  I thought you had added 
|.well-known| as a mechanism that would supersede the standard URI 
pattern **if it were used**.  I had not realized that you had entirely 
_removed_ the standard URI pattern from the spec.

**Comment by dbooth-boston** [comment]
On 10/17/2015 03:42 AM, Ivan Herman wrote:

> And I do not think we would do due diligence if we did not provide a
> standard way of providing a general mechanism. Just relying on various
> implementation options is not satisfactory.
> 
> I maintain my opinion that, at this point, the only reasonable option is
> to publish the document as is.

I understand that view, but see it differently.  I think it is much 
better to leave out a kludgy feature that nobody has indicated an actual 
need and intent to use[2], let implementations compensate for the 
missing feature that is really desired, and eventually, once more people 
recognize that this use of a standard URI pattern is a harmless 
heuristic (rather than URI squatting), perhaps it could finally be made 
more official through a Community Group.

Reference
2. https://lists.w3.org/Archives/Public/public-csv-wg/2015Jun/0085.html

**Comment by JeniT** [comment]
I will not be able to make the call today at which this should be decided.

We need to somehow provide the facility for publishers to provide metadata without having access to HTTP headers: it is not acceptable to drop this facility.

Although I have sympathy with many of David's comments about the requirement for the use of the .well-known mechanism in this particular case, I am equally sympathetic to the TAG's concerns about the precedent that would be set by the CSVW spec specifying fixed search paths.

Practically speaking, supporting the .well-known mechanism is not difficult to implement and does not need to have a big impact on publishers. The costs of keeping it are low.

Procedurally speaking, the TAG exists precisely to offer guidance on these kinds of issues, including to the Director in the case of formal objections from AC members. It seems unwise not to follow their advice.

My opinion, therefore, is that we should retain the existing .well-known mechanism.

I also suggest that we add a note encouraging people to link directly to metadata files rather than CSV files, or to use the Link header, wherever that is possible.

**Comment by iherman** [comment]
Per  http://www.w3.org/2015/10/21-csvw-irc#T14-13-31 the issue is closed.

Needs editorial work, assigned to Gregg

**Comment by danbri** [comment]
"RESOLVED: we leave the .well-known mechanism in the standard, with two editorial changes (Jeni's text on clarification and the forward reference)"

**Comment by danbri** [comment]
Noting https://lists.w3.org/Archives/Public/public-csv-wg/2015Oct/0025.html from @dbooth-boston:

```
  Looking at today's resolution:
  http://www.w3.org/2015/10/21-csvw-irc#T14-13-31
  [[
  RESOLVED: we leave the .well-known mechanism in the standard, with two 
  editorial changes (Jeni's text on clarification and the forward reference)
  ]]

  Given that the standard-URI-pattern feature *is* still in the spec -- in 
  spite of Ivan's (and my) prior misunderstanding -- I think this 
  resolution is reasonable.  The harm of keeping the .well-known mechanism 
  can be minimized.  However, I do have some editorial suggestions to help 
  minimize harm and reduce misunderstandings like the one that Ivan and I had:

  1. At the beginning of section 5, insert a new item to the list of 
  "methods of locating metadata" before item #4, to read:

     "4. metadata located through standard URI patterns, see section 5.3"

  2. Rename section 5.3 to: "Standard URI Patterns and Site-wide Location 
  Configuration"

  3. Add an editorial comment to section 5.3 like: "Publishers of metadata 
  files should bear in mind that use of the .well-known feature to specify 
  non-standard URI patterns may be confusing to users and future 
  maintainers who may only know to look for metadata files matching the 
  standard URI patterns, and may therefore make your metadata files harder 
  for users to find when they look for them directly."

  Thanks,
  David Booth
```

Thanks for the suggestions, David, and for seeking out middle-ground. As Ivan pointed out today there are limits on the extent to which a W3C spec ought to argue against its own approach, but we will try to find some soft editorial tweaks that characterize the situation. Perhaps we could simply cite this issue for background reading on the relevant tradeoffs?

**Comment by dbooth-boston** [comment]
On 10/21/2015 12:05 PM, Dan Brickley wrote:

> Thanks for the suggestions, David, and for seeking out middle-ground. As
> Ivan pointed out today there are limits on the extent to which a W3C
> spec ought to argue against its own approach, but we will try to find
> some soft editorial tweaks that characterize the situation. Perhaps we
> could simply cite this issue for background reading on the relevant
> tradeoffs?

No, I think that would put quite an unnecessary burden on the reader. 
Also, some of my previous comments were based on a misunderstanding of 
what features were actually included in the current spec, which would 
just add more confusion and further burden the reader.

For me, this issue now boils down to two separable points:
- I think the TAG made a mistake in its guidance.  But at this point, 
  that's an issue between me and the TAG, and it doesn't need to further 
  involve the WG.  With respect to this WG, it is water under the bridge.
- The fact that the .well-known feature is in the spec is now only a 
  minor drawback in my opinion, _given_ that the real functionality that 
  we need -- the standard URI pattern feature -- is still there.  (That's 
  a big relief!)
- However, the risk to the user community of using .well-known to 
  specify non-standard naming conventions _is_ important to state -- just 
  like any other risk -- regardless of one's opinion of whether 
  .well-known is architecturally necessary here.   That risk is completely 
  independent of one's view of the architectural necessity or aesthetics 
  of .well-known.  It is an undeniable risk of using that mechanism, and 
  we should point it out just as we would point out any other risk of 
  using any other feature.

Thanks,
David Booth
