### ISSUE TITLE
Rename `tableSchema` to `schema`

### ISSUE THREAD

**Issue by rufuspollock** [w3c/csvw#713]
`schema` is simpler and shorter than `tableSchema` and is equally and sufficiently descriptive for the purposes require (parsimony is always good in specs).

In addition this re-aligns with JSON Table Schema and with Data Package and supports more genericity (schema could be common with other specs e.g. where you are describing geo data with a similar structure)

Cost: very low.

**Comment by gkellogg** [comment]
IIRC, the reason we changed from `schema` to `tableSchema` was because of the conflict with the `schema` prefix defined in the JSON-LD context for schema.org, as we said we were using all prefixes defined in the RDFa context. Also, `schema` is regularly used as a prefix for http://schema.org/.

**Comment by rufuspollock** [comment]
@gkellogg how does it conflict - if it used as a prefix won't it be `schema:` or am i missing something?

**Comment by gkellogg** [comment]
In JSON-LD, "schema" is a term, which expands as defined in the context. You can't have different terms, one which is used when it's a prefix, and the other when it's a bare term. If you use "schema:" it is equivalent to "schema", except where there is a difference in the way that JSON-LD treats values; for example, the `@id` key takes IRIs, and doesn't treat "schema" as a term, but it would treat "schema:" as a prefixed name. In our use, "schema" is a property, and it can't be used both ways.

**Comment by danbri** [comment]
-1

I positively like "tableSchema", since the "schema" word is pretty overloaded. A tableSchema is a table schema. Dublin Core, VOID, schema.org etc also provide for a different sense of schema, also very relevant to tabular data but relevant at a different layer of abstraction. So I think in this case the specificity actively helps, and gives users (publishers and consumers) terminology they can use to describe what's going on.

BTW as a random aside - a few years ago I made a totally unscientific Amazon Turk survey on 'what the word schema means to you'; 

https://docs.google.com/spreadsheets/d/1UPbLw5SEBJGIYYbYI1ziFLzKlHJladY7F-7_GerMhgc/edit?usp=sharing

**Comment by rufuspollock** [comment]
The point here particularly was that this had originated in the Tabular Data Package / Data Package spec. There, this is obviously schema since it may not just be tabular data - thus the major argument is maintaining compatibility.

**Comment by rufuspollock** [comment]
@danbri i would argue that you clearly have `schema` here scoped inside a spec focused on tabular data hence repeating that in the schema naming is redundant :-)

Relatively minor but a small change here would maintain compatibility and would i think also be conceptually simpler (though i understand on this latter point one could argue either way)

**Comment by iherman** [comment]
Closing the issue by virtue of the [resolution of the WG Telco](http://www.w3.org/2015/09/23-csvw-minutes.html#res):

> RESOLUTION: We will close remaining technical issues (#702, #712, #713, #716, #717, #720, #721) that do not have wide support in the Working Group as continuing discussion will threaten eventual success of the group
