### ISSUE TITLE
Alignment of set of datatypes in this spec and those in JSON Table Schema

### ISSUE THREAD

**Issue by rufuspollock** [w3c/csvw#717]
_Data types are one of the most crucial areas of the specification because they are really the core of a specification's value add - the key thing missing in CSV is types! As such getting alignment between this specification and [JSON Table Schema](http://dataprotocols.org/json-table-schema/) / [Tabular Data Package](http://dataprotocols.org/tabular-data-package/) (on which it was based) would be really great._

The set of types are currently very close. The main differences afaict are:
- decimal (not in JTS): this could be resolved in JTS - see https://github.com/dataprotocols/dataprotocols/issues/208 (I note number is also defined in this spec as an alias for double ...)
- duration (not in JTS): not sure about this one. It does exist in SQL so suggest JTS adds this - https://github.com/dataprotocols/dataprotocols/issues/210
- `gYear, gMonth, gMonthDay etc` (not in JTS): could these be treated as formats on date / datetime? Alternatively could add to JTS.
- `hexBinary, QName`: do we really want these? Could these be formats on other types.
- Subtypes of decimal e.g. `unsignedLong, positiveInteger` etc: can these be expressed as types on decimal / number? 
- Subtypes of string e.g. `html, xml`: could these be addressed via format on string (there are many text formats - why special case these?)
- `geopoint, geojson` (in [JTS](http://dataprotocols.org/json-table-schema/#field-types-and-formats) not in spec): geodata is so common (even in CSV!) it would be nice to have some basic support. Plus we would align with JTS

**Comment by JeniT** [comment]
The datatypes in the CSVW specs are based on those used across the W3C standards space (originally defined in XML Schema, used in RDF). Any sub-selection from that set would be somewhat arbitrary, though I note that [XPath Functions & Operators](http://www.w3.org/TR/xquery-operators/#casting-from-primitive-to-primitive) uses a list comprising all the primitive types plus `anyAtomicType`, `integer`, `yearMonthDuration` and `dayTimeDuration`. (This list still includes all the `gDay` etc date/time types and the binary types such as `hexBinary`, and `QName`, so it wouldn't get rid of all of the types that you object to. It would get rid of all the numeric subtypes (which can be supported through `minimum`/`maximum`) but it could be argued that they are the ones most useful for conversion into SQL.) I'm -1 on changing the list to other than the full XML Schema list because I don't know what  objective criteria to apply to filter it.

`html`, `xml` and `json` are special-cased because they're common types. HTML and XML are common enough to have their own datatype in RDF. JSON isn't, but there are a number of JSON-based types listed in JTS. Neither validation nor conversion actually tests whether values marked as `html`, `xml` or `json` actually comply with the relevant syntax. I'm -1 on removing these.

Specifying `geopoint` or `geojson` would take some work, particularly `geopoint` (`geojson` could be a subtype of `json` and only need be given a URL; `geopoint` needs some additional specification, including how to map it consistently into other formats). I'm -0 on adding these mostly because we're at a late stage of standardisation and it would send us back to Working Draft; perhaps we can add them to the list for vNext.

**Comment by rufuspollock** [comment]
@JeniT good points. Note that this item was more about general alignment and, in fact, changes to the JSON Table Schema type list to align. Only changes here were really on geopoint. One could live without that but it would be nice (and re geojson that's a good point - maybe it should be a `format` of `object / json` in JTS)

**Comment by iherman** [comment]
Closing the issue by virtue of the [resolution of the WG Telco](http://www.w3.org/2015/09/23-csvw-minutes.html#res):

> RESOLUTION: We will close remaining technical issues (#702, #712, #713, #716, #717, #720, #721) that do not have wide support in the Working Group as continuing discussion will threaten eventual success of the group
