### ISSUE TITLE
Value constraints on date/time values

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#725]
1. The [model document](http://w3c.github.io/csvw/syntax/#datatypes) describes the **minimum**, **maximum** etc annotations as holding numbers, when they can also hold date/time values. I suggest a small editorial change to make this clear.
2. It isn't clear in the spec whether the format of date/times provided as the value of `minimum`, `maximum` etc in the metadata has to match the `format` of the datatype. For example, should you have:
   
   ```
   { "datatype": "date", "format": "dd/MM/yyyy", "minimum": "2000-01-01" }
   ```
   
   or
   
   ```
   { "datatype": "date", "format": "dd/MM/yyyy", "minimum": "01/01/2000" }
   ```
   
   I suggest that we add a note in the metadata document that states that min/max date/time values must be provided in the standard XML Schema (ISO8601) format for the relevant datatype. I believe this is just a clarification of the text.

**Comment by gkellogg** [comment]
+1, we'll need some tests for this.

**Comment by iherman** [comment]
+1 on both counts.

**Comment by 6a6d74** [comment]
+1 to both (1) & (2) ... although I note that the mix-and-match approach to date formats will be confusing to many. 

_We_ are saying use standard XML Schema (ISO 8601) date format for the min / max value because this is in control of the metadata editor, whereas the date format in the CSV data itself could use any number of common formats & that's what the `format` property is for. 

Another way of saying this is that the min / max date is compared to the value in the data _after_ that has been internally normalised to ISO 8601 format ...

**Comment by gkellogg** [comment]
I agree, minimum and maximum, etc. should be entered using XSD format, and not depend on format parsing.

**Comment by gkellogg** [comment]
@JeniT, take a look at this. I figured that it is really about property constraints specified using strings and that they must be in an appropriate XSD representation. I included your example using `date`. Elsewhere, it's clear that value constraints can be made on numeric, date/time and durations, so this just clarifies how the constraint must (should) be specified.
