### ISSUE TITLE
CSV decimal dot resolution recommendation, for import/export agents

### ISSUE THREAD

**Issue by ppKrauss** [w3c/csvw#742]
(sorry if it is not here a good local to discuss, please ignore and delete)

---

There are here a possibility to appreciate the classical problem of the decimal dot/comma in  numeric columns of  CSV files?

It is a problem  about _to recommend_ to LibreOffice, GoogleDrive, Microsoft, etc. what is correct or what options to offer to user?... When we change agent locale-configs (language of menus, currency, etc.). Data is lost in the import/export process.... EXAMPLE:

| A | B |
| --- | --- |
| xx | 1.2 |
| yy | 3.0 |

is exported by english agent as

```
A,B
xx,1.2
yy,3.0
```

Them imported by portuguese agent  as 

| A | B |
| --- | --- |
| xx | 12 |
| yy | 30 |

losing original information. 

Without a basic reliable behaviour in export/import, is difficult see a large (non-programmers) user community of CSV ... A simple recommendation, perhaps, is to say _"import standard CSV in a standard way, not enforcing  locale convertions before to obtain cell's original data-type from the parser"_....

**Comment by iherman** [comment]
@ppKrauss I am not sure whether this comment is suggesting a change/improvement on one of the CSVW documents, or is it a general observation. Can you elaborate? Thanks.

**Comment by gkellogg** [comment]
@ppKrauss, CSVW [includes a mechanism](http://www.w3.org/TR/tabular-data-model/#formats-for-numeric-types) for specifically specifying the characters to use as decimal separator and group character. There are a number of tests to make sure that implementations do this properly, and not confuse different digits. Moreover, the spec requires the use of [number format patterns](http://www.unicode.org/reports/tr35/tr35-numbers.html#Number_Format_Patterns) from [UAX35](http://www.unicode.org/reports/tr35/tr35-31/tr35.html) that provides for a number of localle-specific number formats to be parsed correctly.

Presuming that agents, such as the protuguese agent you note above conform to these standards, you should not see the problems you note.

If this addresses your concern, please close the issue. Otherwise, perhaps you can clarify your concerns further.

**Comment by iherman** [comment]
After 10 days of no answer, closing this
