### ISSUE TITLE
Encoding and formatting issues on test032

### ISSUE THREAD

**Issue by davideceolin** [w3c/csvw#775]
Hello,

I'd have two small issues on test032:
- in the metadata, start_date is formatted as "yyyy-MM-ddTHH:mm", but then in the result also the seconds are reported ("2014-04-12T19:30:00"). Is there any particular reason for this?
- the first location name is "Lupo's Heartbreak Hotel", but while R reads as it that, in the result it's "Lupoâ€™s Heartbreak Hotel". ("Lupo\u2019s Heartbreak Hotel" vs. "Lupo\u00e2\u0080\u0099s Heartbreak Hotel"). I suppose it is a matter of encoding: what's the default here?
  Thanks,

Davide

**Comment by gkellogg** [comment]
> in the metadata, start_date is formatted as "yyyy-MM-ddTHH:mm", but then in the result also the seconds are reported ("2014-04-12T19:30:00"). Is there any particular reason for this?

The format is used for recognizing the input. In step 4.6.8.7 of the CSV2RDF document, it says the following:

> The literal nodes derived from the cell values must be expressed according to the cell value's datatype as defined below: Interpreting datatypes.

As the value is xsd:dateTime, it is represented using the normalized format for that datatype. This is true for all datatyped literals.

> the first location name is "Lupo's Heartbreak Hotel", but while R reads as it that, in the result it's "Lupoâ€™s Heartbreak Hotel". ("Lupo\u2019s Heartbreak Hotel" vs. "Lupo\u00e2\u0080\u0099s Heartbreak Hotel"). I suppose it is a matter of encoding: what's the default here? Thanks,

The CSV file for 032 contains "Lupo’s Heartbreak Hotel", which escapes to ASCII as "Lupo\u2019s Heartbreak Hotel", as you note. Both the Turtle and the JSON output use the same representation. Encoding is UTF-8, unless otherwise noted.

**Comment by davideceolin** [comment]
Thanks.
