### ISSUE TITLE
How to handle merged cells?

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#803]
There's nothing in the HTML Note about how to handle cells that are merged over several rows or columns (ie that have `colspan` or `rowspan` set to more than 1). I think the three options are:
1. error on tables that contain cells of this type
2. put the value of these cells into the first row/column that they appear in
3. put the value of these cells into all the cells that they span into

I think the second is probably the thing people will expect.

**Comment by gkellogg** [comment]
I think we may just leave this undefined, and look for future feedback to refine this, but assumptions should be discussed in a note/issue within the document. The algorithm is intended for a uniformly constructed table with header rows preceding data rows, data rows containing simple text, and a uniform number of columns.

Tracking `@colspan/@rowspan` significantly complicates processing. If done, I would say that `@rowspan` is the least useful. `@colspan` would most likely use the value for the first column in the span and need to keep track of the span so that subsequent columns were deposited as the appropriate value.

For this stage, IMO, keeping it simple solves many interesting use cases. If real-world feedback is that more complicated processing is warranted, the CG may choose to update the note (if the WG makes some provision for that).

Leaving it undefined allows an extension space for developers to work in.
