### ISSUE TITLE
Should the JSON-LD keywords be aliased?

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#81]
The keywords that are used are:
- `@id` - used to identify CSV files - I propose we alias this to `url`
- `@language` - used to identify the default language of the content of the metadata document (not the CSV files it describes) - I'm wary about aliasing this as we already have `language`; currently `@language` can only appear within the top level `@context` (which cannot be aliased) so I suggest we just keep it as is
- `@base` - used to provide the base URL for the metadata document (not the CSV files it describes) - again this can only appear within `@context` so I suggest we keep it as is
- `@type` - used to indicate whether an object is a table description, column description, schema etc - I don't think we want to make this mandatory, so anything that uses an RDF-based pipeline will have to insert in the relevant types anyway, so I propose that we simply remove this from the document

This relates to #48, see discussion at http://www.w3.org/2014/11/12-csvw-minutes.html#item10

**Comment by iherman** [comment]
> On 30 Nov 2014, at 18:02 , Jeni Tennison notifications@github.com wrote:
> 
> The keywords that are used are:
> 
>   • @id - used to identify CSV files - I propose we alias this to url

I can live either way...

>   • @language - used to identify the default language of the content of the metadata document (not the CSV files it describes) - I'm wary about aliasing this as we already have language; currently @language can only appear within the top level @context (which cannot be aliased) so I suggest we just keep it as is

+1

>   • @base - used to provide the base URL for the metadata document (not the CSV files it describes) - again this can only appear within @context so I suggest we keep it as is

+1

>   • @type - used to indicate whether an object is a table description, column description, schema etc - I don't think we want to make this mandatory, so anything that uses an RDF-based pipeline will have to insert in the relevant types anyway, so I propose that we simply remove this from the document

+1; actually, we do not have a separate row and cell description any more, so there is no real usage for it.

Ivan

> This relates to #48, see discussion at http://www.w3.org/2014/11/12-csvw-minutes.html#item10
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
Note that `@language` is only used within an expanded value or within a context document, so aliasing it doesn't work for us. Really, we probably want to use `dc:language` within the metadata doc.

Also, `@base` is only used within the context, which is already JSON-LD.

Of course, either of these could be used in an embedded context, in which aliases could be useful, but I'm not sure this is a typical usage.

Aliasing `@type` and `@id` makes sense, as it is used in node definitions directly. I'd be more included to use `id` rather than `url`, though, but I don't feel strongly about this.

**Comment by 6a6d74** [comment]
Question: A row in a CSV file describes a particular object - how would I assert what _type_ of object it is?
- `@type` in the metadata document is used for table, schema, column etc.
- `datatype` provides a list of types for literals - and is a fixed list

I think that we might also want to assert that, if a value is a URI, then the object identified by that URI is of a particular type.

(apologies if this is already specified somewhere)

**Comment by iherman** [comment]
> On 01 Dec 2014, at 11:58 , Jeremy Tandy notifications@github.com wrote:
> 
> Question: A row in a CSV file describes a particular object - how would I assert what type of object it is?
> 
>   • @type in the metadata document is used for table, schema, column etc.
>   • datatype provides a list of types for literals - and is a fixed list
> I think that we might also want to assert that, if a value is a URI, then the object identified by that URI is of a particular type.

We may do that in the RDF conversion, by assigning a particular type, but it is not required...

Ivan

> (apologies if this is already specified somewhere)
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by 6a6d74** [comment]
> We may do that in the RDF conversion, by assigning a particular type, but it is not required...

How? We could add the triple `rdf:type` into the metadata description but this type statement needs to be associated with the data from the CSV file rather than the section of the metadata doc (e.g. `schema`, `column` etc.).

Sorry - I'm probably being dumb. 

(If this turns into a detailed discussion I'll create a new issue)

**Comment by iherman** [comment]
> On 01 Dec 2014, at 12:46 , Jeremy Tandy notifications@github.com wrote:
> 
> We may do that in the RDF conversion, by assigning a particular type, but it is not required...
> 
> How? We could add the triple rdf:type into the metadata description but this type statement needs to be associated with the data from the CSV file rather than the section of the metadata doc (e.g. schema, column etc.).

Ah, I think we misunderstood one another. I thought you were thinking about adding a generic type of the sort (rowid rdf:type csvw:row).

If we want a more general thing then, indeed, we need this as part of the metadata with some specific key. But... is there a real need for something that general? If the author really wants that then... just add a column for typing and uritemplate to turn the predicate for that column rdf:type

Ivan

> Sorry - I'm probably being dumb.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by 6a6d74** [comment]
Discussion on specifying semantic type moved to #82

**Comment by gkellogg** [comment]
Given that `@id` is used to denote the identifier of both the metadata and the table it relates to, and we want to alias this to something like `url`, I propose that we simply create a new `url` property, and not say anything about `@id`. If it is used, then it denotes the Metadata entity, rather than the table.

**Comment by gkellogg** [comment]
The main thing to settle here, IMO, is the use of `@id` (aliased or otherwise) vs. some other property. Just documenting csvw:table made this clear, as from the definition, it's identical to csvw:resources, but clearly one relates the TableGroup metadata to the Table metadata, there the other relates an annotated TableGroup with an annotated Table.

Both `@id` and `@type` can have a role in the metadata (perhaps using aliases) in describing identifiers for metadata elements, but may not be necessary; but, we should give some guidance on best practices if they are used.

**Comment by gkellogg** [comment]
Discussed in http://www.w3.org/2015/01/28-csvw-minutes.html. The use of `@id` is changed to `url`, which is it's own property. `@id` can exist as per JSON-LD but does _not_ directly relate to the referenced resource. `@type` is left unchanged, also without alias.

RESOLUTION: make @id optional, add url property to point to CSV / template files etc
RESOLUTION: otherwise close #81 with no other aliasing
